#include "../src/game.h"
#include "../src/serial.h"
#include <cstdlib>
#include <cstring>
#include <memory>
static int checks=0;
static void check(bool v,const char* text){checks++;if(!v){printf("FAIL museum: %s\n",text);exit(1);}}
static Competition league(int a,int b,int year){Competition C;C.kind=1;C.name="Championnat test du musée";C.format=FMT_LEAGUE;Stage s;s.type=ST_LEAGUE;s.groups={{a,b}};MatchRes m;m.home=a;m.away=b;m.hg=3;m.ag=0;m.played=true;m.group=0;C.matches.push_back(m);Round r;r.m={0};r.time=10;s.rounds.push_back(r);C.stages.push_back(s);C.done=true;C.winner=year==2?a:b;return C;}
static Competition cup(int a,int b,bool win){Competition C;C.kind=2;C.name="Coupe test du musée";C.format=FMT_CUP;Stage s;s.name="Finale";s.type=ST_KO;Tie t;t.a=a;t.b=b;t.m1=0;t.winner=win?a:b;s.ties.push_back(t);MatchRes m;m.home=a;m.away=b;m.hg=1;m.ag=1;m.ph=win?5:3;m.pa=win?4:4;m.played=true;m.tie=0;m.neutral=true;C.matches.push_back(m);Round r;r.m={0};r.time=50;s.rounds.push_back(r);C.stages.push_back(s);C.done=true;C.winner=t.winner;return C;}
int main(){g_world.build();int a=-1,b=-1;for(auto& P:g_basePyramids)if(P.country=="FRA")for(auto& pool:P.pools)if(pool.tier==0){a=pool.clubs[0];b=pool.clubs[1];break;}check(a>=0&&b>=0,"clubs available");g_career.opts=Career::Opts();g_career.newClubCareer(a,2026);check(g_career.museumEnabled(),"club museum enabled");check(g_career.clubHistories[a].trophies.empty(),"no invented historical titles");check(g_career.clubHistories[a].seasons.size()==1,"initial season exists");g_career.opts.lite=1;check(!g_career.museumEnabled(),"no museum in simple championship");g_career.opts.lite=0;
 g_career.clubHistories.clear();g_career.managerName="Thorn Test";g_career.pyramids.clear();Pyramid P;P.country="FRA";P.tiers.resize(3);for(int i=0;i<3;i++)P.tiers[i].name="Division test "+std::to_string(i);Pool pool;pool.tier=2;pool.clubs={a,b};pool.comps={0};pool.groups={{a,b}};P.pools.push_back(pool);g_career.pyramids.push_back(P);g_career.seasonAwards.clear();g_career.cdfRegional.clear();g_career.ucl=g_career.uel=g_career.uecl=g_career.intertoto=g_career.uefaSuper=-1;
 int pid=g_world.teams[a].squad[5].id;
 for(int y=0;y<5;y++){
  g_career.year=2026+y;g_career.season.now=10;g_career.season.comps.clear();g_career.season.comps.push_back(league(a,b,y));g_career.museumState(a);
  for(auto& p:g_world.teams[a].squad){p.apps=1;p.goals=p.id==pid?3:0;p.assists=p.id==pid?1:0;}
  MEv e;e.match=0;e.pid=pid;e.team=a;e.type=0;g_career.season.comps[0].events.push_back(e);
  auto rngState=g_rng.s;g_career.museumMatch(0,0);g_career.museumEvents(0,0);g_career.museumAttendance(0,0,1000+y*500);check(g_rng.s==rngState,"museum observers preserve match random state");auto snapshots=g_career.clubHistories[a].timeline.size();auto stats=g_career.clubHistories[a].players;g_career.museumMatch(0,0);g_career.museumEvents(0,0);g_career.museumAttendance(0,0,99999);check(g_career.clubHistories[a].timeline.size()==snapshots,"duplicate callbacks don't add timeline");check(g_career.clubHistories[a].seasons.back().homeMatches==1,"gate booked once");check(g_career.clubHistories[a].players[5].apps==stats[5].apps,"duplicate events don't add apps");
  if(y>=3){g_career.season.comps.push_back(cup(a,b,y==4));g_career.cupVenue[1]="Stade des finales";g_career.museumMatch(1,0);g_career.museumEvents(1,0);MuseumMatch exact;exact.exactLineup=1;exact.attendance=9000;snprintf(exact.venue,sizeof exact.venue,"Stade des finales");exact.xi[0][0]=pid;snprintf(exact.lineupNames[0][0],48,"Composition réelle");g_career.museumEnrich(1,0,exact);g_career.museumCompetition(1);g_career.museumCompetition(1);}
  if(y==4){g_world.teams[a].stadium="Nouveau stade du musée";g_career.museumState(a);}
  g_career.museumSeasonEnd(false);if(y==0||y==2)g_career.pyramids[0].pools[0].tier--;g_career.museumSeasonEnd(true);auto events=g_career.clubHistories[a].timeline.size();g_career.museumSeasonEnd(true);check(g_career.clubHistories[a].timeline.size()==events,"season finalisation idempotent");
 }
 auto& H=g_career.clubHistories[a];check(H.seasons.size()==5,"five seasons retained");int moves=0;for(auto& s:H.seasons){check(s.finished,"season archived");moves+=s.promoted;check(s.played==1&&s.points==3&&s.gf==3&&s.ga==0,"league totals preserved");check(s.scorerPid==pid&&s.scorerGoals==3,"season scorer stored");}check(moves==2,"two promotions");check(H.trophies.size()==2,"one league title and one cup");check(H.finals.size()==2,"won and lost final stored");check(H.finals[0].winner==b&&H.finals[1].winner==a,"penalty final winner");check(H.finals[1].exactLineup&&H.trophies[1].finalMatch.exactLineup,"actual final lineup retained in trophy");check(H.stadiums.size()==2,"two stadium periods");check(H.shirts.size()==5,"five kit snapshots");check(H.managers.size()==1&&H.managers[0].promotions==2&&H.managers[0].trophies==2,"manager achievements");check(H.seasons.back().averageAttendance==3000,"attendance year reset");
 MuseumPlayer* legend=nullptr;for(auto& p:H.players)if(p.pid==pid)legend=&p;check(legend&&legend->goals==15&&legend->apps==5&&legend->seasons==5,"cumulative player contribution");check(legend->legendScore()>legend->apps,"legend score uses contribution");check(H.records.size()>10,"player match season and club records");check(!g_career.clubHistories[b].trophies.empty(),"independent opponent archive");
 g_career.museumTransfer(g_world.teams[a].squad[5],a,b,1000);bool transfer=false;for(auto& r:H.records)if(r.kind==MR_SELL&&r.value==1000)transfer=true;check(transfer,"transfer record");g_world.teams[a].sta.museum=0;auto count=H.timeline.size();g_career.museumState(a);check(H.timeline.size()==count,"museum downgrade doesn't erase archive");
 check(g_career.save("build/test-build5.sav"),"save all career museum state");check(g_career.load("build/test-build5.sav"),"load all career museum state");check(g_career.clubHistories[a].seasons.size()==5&&g_career.clubHistories[a].trophies.size()==2&&g_career.clubHistories[a].finals.size()==2,"save reload preserves achievements");check(g_career.clubHistories[a].timeline.size()==count,"timeline preserved");
 g_career.museumLeave(a);check(g_career.clubHistories[a].managers.back().toYear==2030,"manager departure archived");g_career.userTeam=b;g_career.museumState(b);check(g_career.clubHistories[a].seasons.size()==5,"club change retains former museum");
 if(FILE* f=fopen("build/test-legacy-v28.sav","rb")){fclose(f);check(g_career.load("build/test-legacy-v28.sav"),"build4 save version28 load");check(g_career.clubHistories.empty(),"old save has no invented museum history");g_career.museumState(g_career.userTeam);check(g_career.clubHistories.size()==1,"legacy starts archives on use");}
 g_career.userTeam=a;g_career.mgr.projects.clear();g_career.mgr.budget=100000;g_world.teams[a].sta.museum=1;Project project;project.kind=PJ_MUSEUM;std::string error;check(g_career.startProject(project,error),"second museum level can be constructed");for(int month=0;month<4;month++)stadiumMonth(g_career);check(g_world.teams[a].sta.museum==2,"museum construction reaches level2");check(!g_career.startProject(project,error),"no third museum level");
 // Reject truncated / excessively sized museum vectors before allocating them.
 FILE* f=tmpfile();Writer w{f};unsigned n=1;w.pod(n);ClubHistory h;h.clubId=a;w.pod(h.clubId);w.pod(h.firstYear);w.pod(h.seenYear);w.pod(h.unbeaten);w.pod(h.winStreak);w.pod(h.cleanStreak);w.pod(h.firstFlags);unsigned bad=100000000;w.pod(bad);rewind(f);Reader r{f};museumLoad(r,g_career);check(!r.ok,"malformed museum rejected");fclose(f);
 printf("PASS build5 museum: %d checks\n",checks);return 0;}
