#include "../src/game.h"
#include "../src/serial.h"
#include <cstdlib>
#include <cstring>
#include <set>
static int checks=0;static void check(bool b,const char* msg){checks++;if(!b){printf("FAIL director: %s\n",msg);exit(1);}}
static int club(const char* nation,int tier){for(auto& P:g_basePyramids)if(P.country==nation&&P.dom<0)for(auto& pool:P.pools)if(pool.tier==tier&&!pool.clubs.empty())return pool.clubs[0];return -1;}
static void start(int t){g_career.opts=Career::Opts();g_career.life.isPlayer=0;g_career.newClubCareer(t,2026);g_career.season.now=.2;g_career.directorSync();}
static void generous(){auto& L=g_career.director.limits;g_career.mgr.budget=1000000;g_career.mgr.wageCapK=10000000;L.budgetBase=1000000;L.boardFees=800000;L.maxFee=100000;L.maxWage=100000;L.wageCap=L.boardWages=10000000;L.used=0;L.budgetPct=80;}
static int countPid(int pid){int count=0;for(auto& t:g_world.teams)for(auto& p:t.squad)count+=p.id==pid;return count;}
int main(){g_world.build();int pro=club("FRA",0),amateur=club("FRA",8),german=club("GER",0);check(pro>=0&&amateur>=0&&german>=0,"fixtures available");start(pro);auto& K=g_career;auto& D=K.director;check(K.directorEnabled()&&D.profile.name[0],"professional DS in existing staff");for(auto m:D.mode)check(m==DM_MANUAL,"manual default for each domain");for(auto s:D.profile.skill)check(s>=10&&s<=99,"bounded skill profile");auto rng=g_rng.s;K.directorAnalyse(false);check(g_rng.s==rng,"read-only analysis leaves match RNG untouched");check(!D.needs.empty()&&!D.report.empty(),"formation and finance report");auto moneyBefore=K.mgr.budget;auto size=g_world.teams[pro].squad.size();K.season.now=1;K.directorTick();check(moneyBefore==K.mgr.budget&&size==g_world.teams[pro].squad.size(),"all-manual makes no transaction");K.opts.lite=1;check(!K.directorEnabled(),"simple mode unaffected");K.opts.lite=0;K.life.isPlayer=1;check(!K.directorEnabled(),"no DS career/player control mode");K.life.isPlayer=0;
 generous();std::string msg;check(K.directorCanSpend(100,100,msg),"rich club affordable proposal");D.limits.maxWage=10;check(!K.directorCanSpend(0,11,msg),"salary ceiling");D.limits.maxWage=100000;D.limits.used=800000;check(!K.directorCanSpend(1,0,msg),"season allocation exhausted");D.limits.used=0;D.limits.wageCap=1;check(!K.directorCanSpend(0,1,msg),"annual payroll ceiling includes existing staff");generous();K.mgr.dncg=1;check(!K.directorCanSpend(1,0,msg),"French DNCG cannot be bypassed");K.mgr.dncg=0;
 auto xi=g_world.pickLineup(pro,g_world.teams[pro].formation,RULESET_CAREER);int key=g_world.teams[pro].squad[xi[1]].id;check(K.directorProtected(key),"starter automatically protected");K.directorPolicy(key,DS_FOR_SALE,true);check(K.directorProtected(key),"human NE PAS VENDRE overrides sale status");for(auto& m:D.mode)m=DM_AUTO;TransferOffer offer;offer.pid=key;offer.club=german;offer.fee=100000;K.mgr.offers.push_back(offer);K.season.now=1.1;K.directorTick();check(g_world.findPlayer(key)==pro,"complete sales respect lock");K.mgr.offers.clear();for(auto& m:D.mode)m=DM_MANUAL;
 int freeTeam=freeAgentsTeam();g_world.ensureSquad(freeTeam);check(!g_world.teams[freeTeam].squad.empty(),"free agents available");auto& free=g_world.teams[freeTeam].squad.back();free.age=24;free.gender=0;free.speed=free.shoot=free.pass=free.tackle=free.keep=40;free.wageK=50;free.contract=0;int pid=free.id;
 D.profile.skill[DK_NEGOTIATE]=D.profile.skill[DK_AGENTS]=D.profile.skill[DK_CONTRACT]=100;
 check(!K.directorStart(pid,false,msg),"manual responsibility refuses delegation");D.mode[DD_OFFERS]=D.mode[DD_FEES]=D.mode[DD_CONTRACTS]=D.mode[DD_AGENTS]=DM_NEGOTIATE;check(K.directorStart(pid,false,msg),"human-selected negotiation queued");moneyBefore=K.mgr.budget;int n=(int)D.negotiations.size()-1;K.season.now=3;K.directorTick();check(D.negotiations[n].phase==DN_APPROVAL,"negotiation-only waits for approval");check(K.mgr.budget==moneyBefore&&g_world.findPlayer(pid)==freeTeam,"no premature contract or spending");D.request.position=DP_BU;D.request.role=1;D.request.profile=DP_YOUNG;D.request.loanWagePct=30;K.directorPolicy(key,DS_FOR_SALE,true);check(K.save("build/test-build7.sav"),"save pending DS career");check(K.load("build/test-build7.sav"),"reload version30");check(D.request.position==DP_BU&&D.request.profile==DP_YOUNG&&D.request.loanWagePct==30,"coach preferences persisted");check(D.negotiations[n].phase==DN_APPROVAL&&D.negotiations[n].pid==pid,"dossier survives load");check(K.directorProtected(key)&&D.mode[DD_OFFERS]==DM_NEGOTIATE,"locks and responsibilities persisted");generous();moneyBefore=K.mgr.budget;int acceptedWage=D.negotiations[n].wage;D.negotiations[n].wage=0;check(!K.directorApprove(n,msg)&&!D.negotiations[n].approved,"counterproposal revokes previous human approval");check(g_world.findPlayer(pid)==freeTeam&&K.mgr.budget==moneyBefore,"refused offer spends nothing");D.negotiations[n].wage=acceptedWage;K.season.now=3.25;K.directorTick();check(D.negotiations[n].phase==DN_APPROVAL&&g_world.findPlayer(pid)==freeTeam,"revised offer needs renewed approval");check(K.directorApprove(n,msg),"approval uses normal transfer transaction");check(g_world.findPlayer(pid)==pro&&countPid(pid)==1&&K.mgr.budget<moneyBefore,"signature has exactly one player and books cost");check(!K.directorApprove(n,msg),"cannot sign twice");
 // Revoke permissions while a dossier is running.
 auto& other=g_world.teams[freeTeam].squad.back();other.age=24;other.speed=other.pass=other.shoot=other.tackle=40;other.keep=20;int otherPid=other.id;check(K.directorStart(otherPid,false,msg),"second target");int last=(int)D.negotiations.size()-1;D.mode[DD_CONTRACTS]=DM_MANUAL;K.season.now=3.3;K.directorTick();check(D.negotiations[last].phase==DN_PAUSED&&g_world.findPlayer(otherPid)==freeTeam,"revoked delegation pauses without transaction");D.negotiations[last].phase=DN_CANCELLED;
 // Contract automation extends an expiring starter once, even over several ticks.
 generous();auto& starter=g_world.teams[pro].squad[xi[0]];starter.years=1;starter.age=26;int renewPid=starter.id;D.mode[DD_RENEWALS]=DM_AUTO;K.directorAnalyse(false);K.season.now=3.4;K.directorTick();int idx;check(g_world.findPlayer(renewPid,&idx)==pro&&contractYears(g_world.teams[pro].squad[idx])==2,"expiring key contract renewed");K.season.now=3.5;K.directorTick();check(contractYears(g_world.teams[pro].squad[idx])==2,"stale report never renews repeatedly");
 // Incoming loan wage split and option exercise must preserve ownership and unique IDs.
 int lender=-1;for(auto& P:g_basePyramids)if(P.country=="FRA"&&P.dom<0)for(auto& pool:P.pools)if(pool.tier==0)for(int t:pool.clubs)if(t!=pro){lender=t;break;}check(lender>=0,"loan lender");g_world.ensureSquad(lender);auto& loanP=g_world.teams[lender].squad.back();loanP.speed=loanP.shoot=loanP.pass=loanP.tackle=loanP.keep=20;loanP.age=20;loanP.wageK=101;loanP.contract=0;int loanPid=loanP.id;K.mgr.dncg=0;generous();auto sourceWage=K.wageBill(lender),targetWage=K.wageBill(pro);check(K.loanIn(loanPid,msg,30),"normal incoming loan transaction");check(K.wageBill(pro)==targetWage+30&&K.wageBill(lender)==sourceWage-30,"both clubs charged their actual loan wage shares");check(K.wageBill(pro)+K.wageBill(lender)==targetWage+sourceWage,"salary rounding conserves total wage");check(!K.directorRenew(loanPid,msg),"borrower cannot renew the owner contract");check(countPid(loanPid)==1,"loan no duplicate");DirectorLoanTerms terms;terms.pid=loanPid;terms.from=lender;terms.to=pro;terms.year=2026;terms.option=25;terms.wagePct=30;D.loanTerms.push_back(terms);check(K.directorExercise(loanPid,msg),"negotiated option exercised");check(K.loansIn(pro)==0&&countPid(loanPid)==1&&K.wageBill(pro)==targetWage+101,"option removes loan and charges full owner wage");check(!K.directorExercise(loanPid,msg),"option cannot be paid twice");
 // A complete delegation commits a target autonomously, with the same financial guards.
 for(auto& m:D.mode)m=DM_MANUAL;generous();D.mode[DD_OFFERS]=D.mode[DD_FEES]=D.mode[DD_CONTRACTS]=D.mode[DD_AGENTS]=DM_AUTO;K.season.now=.3;D.lastTick=-100;check(K.directorStart(otherPid,false,msg),"full delegation target opens");int full=(int)D.negotiations.size()-1;D.negotiations[full].chosen=0;K.season.now=3;K.directorTick();check(D.negotiations[full].phase==DN_DONE&&g_world.findPlayer(otherPid)==pro,"full delegation signs without approval");check(countPid(otherPid)==1,"automatic transfer unique ownership");
 // Young reserve is loaned to a club where he is not third choice, and returns cleanly.
 for(auto& m:D.mode)m=DM_MANUAL;auto& bench=g_world.teams[pro].squad.back();bench.age=20;bench.pos=POS_FW;bench.speed=bench.shoot=bench.pass=bench.tackle=bench.keep=55;bench.wageK=100;bench.contract=0;int youngPid=bench.id;K.directorPolicy(youngPid,DS_FOR_LOAN,false);for(auto& q:g_world.teams[lender].squad)if(q.pos==POS_FW){q.speed=q.shoot=q.pass=q.tackle=q.keep=20;}g_world.teams[lender].rating=50;int destination=K.directorLoanClub(youngPid);check(destination>=0,"suitable club proposed for young loan");g_world.ensureSquad(destination);int stronger=0;for(auto& q:g_world.teams[destination].squad)if(q.pos==POS_FW&&q.overall()>=bench.overall())stronger++;check(stronger<2,"young loan never third choice");K.season.now=.4;check(K.loanOut(youngPid,msg,destination,70),"recommended outgoing loan uses existing transaction");check(g_world.findPlayer(youngPid)==destination&&countPid(youngPid)==1,"outgoing loan owns one squad location");std::vector<std::string> loanNews;K.returnLoans(loanNews);check(g_world.findPlayer(youngPid)==pro&&K.loans.empty()&&countPid(youngPid)==1,"loan return restores unique owner");
 // Amateur searches remain local and free. No real club compositions are rewritten.
 start(amateur);check(D.profile.name[0]&&D.profile.philosophy==DP_LOCAL,"amateur local director");K.directorAnalyse(true);check(D.limits.maxFee==0&&D.limits.maxWage==0,"amateur volunteer envelope");for(auto& c:D.targets){auto& T=g_world.teams[c.club];check(c.fee==0&&c.wage==0,"amateur accessible target");check(T.freeAgents||T.parent==amateur||T.nation==g_world.teams[amateur].nation&&(T.region==g_world.teams[amateur].region||T.district==g_world.teams[amateur].district),"amateur local network");}
 auto profile=D.profile;D.limits.maxFee=0;D.limits.maxWage=0;D.mode[DD_STAFF_RENEW]=DM_AUTO;for(int y=2027;y<=2031;y++){K.year=y;K.directorSync();check(D.profile.name[0]&&D.profile.age==profile.age+y-2026,"multiseason profile and automatic staff renewal");check(D.limits.maxFee==0,"zero fee limit persists across seasons");}check(K.save("build/test-build7-amateur.sav")&&K.load("build/test-build7-amateur.sav"),"multiseason amateur save reload");
 start(german);generous();K.mgr.dncg=2;check(!K.hasDncg()&&K.directorCanSpend(1,0,msg),"foreign championship ignores DNCG");
 if(FILE* f=fopen("build/test-legacy-v29.sav","rb")){fclose(f);check(K.load("build/test-legacy-v29.sav"),"previous build6 save version29 compatible");check(D.club==-1&&D.negotiations.empty(),"legacy director state lazily initializes");}
 // Defensive loading rejects a malformed delegation and excessively large vectors.
 FILE* f=tmpfile();K.director=DirectorState();K.director.mode[0]=99;Writer w{f};directorSave(w,K);rewind(f);Reader reader{f};directorLoad(reader,K);check(!reader.ok,"invalid delegation rejected");fclose(f);
 printf("PASS build7 director: %d checks\n",checks);
}


