#include "../src/game.h"
#include "../src/match.h"
#include <memory>
#include <cstdlib>
#include <cstring>
static int checks=0;
static void check(bool v,const char* text){checks++;if(!v){printf("FAIL build4: %s\n",text);exit(1);}}
int main(){
 g_world.build();int a=-1,b=-1;for(auto& P:g_basePyramids)if(P.country=="FRA")for(auto& pool:P.pools)if(pool.tier==0){a=pool.clubs[0];b=pool.clubs[1];break;}
 check(a>=0&&b>=0,"two playable clubs");g_career.opts=Career::Opts();g_career.newClubCareer(a,2026);check(careerRules(),"long club career profile");g_career.opts.lite=1;check(!careerRules(),"championship profile simple");g_career.opts.lite=0;g_career.euroOnly=true;check(!careerRules(),"standalone cups profile simple");g_career.euroOnly=false;
 for(int f=0;f<NUM_FORMATIONS;f++)for(int s=0;s<11;s++){int dp=slotPosition(f,s);check(dp>=0&&dp<DP_COUNT,"all slots have valid detailed position");check(s==0?dp==DP_GB:dp!=DP_GB,"only goalkeeper slot is GB");}
 check(slotPosition(3,1)==DP_PIS_G&&slotPosition(3,5)==DP_PIS_D,"five defenders include wingbacks");check(slotPosition(0,1)==DP_DG&&slotPosition(0,4)==DP_DD,"four defenders include ordinary fullbacks");check(slotPosition(5,8)==DP_MOC,"4231 number ten independent of player family");
 for(int family=0;family<4;family++)for(int id=1;id<=25;id++){Player p;p.id=id;p.pos=family;initPositions(p);check(positionFamily(p.positions.primary)==family,"generated natural position fits family");check(positionFamiliarity(p,p.positions.primary)>=90,"natural familiarity");for(int dp=0;dp<DP_COUNT;dp++)check(positionFamiliarity(p,dp)>=0&&positionFamiliarity(p,dp)<=100,"familiarity bounds");}
 Player mid;mid.id=7;mid.pos=POS_MF;mid.age=17;mid.positioning=80;initPositions(mid);mid.positions.primary=DP_MC;for(int i=0;i<DP_COUNT;i++)mid.positions.familiarity[i]=30;Player close=mid,far=mid,older=mid;older.age=34;for(int i=0;i<20;i++){learnPosition(close,DP_MDC,90,5);learnPosition(far,DP_DG,90,5);learnPosition(older,DP_MDC,90,5);}check(close.positions.familiarity[DP_MDC]>far.positions.familiarity[DP_DG],"near position learns faster");check(close.positions.familiarity[DP_MDC]>older.positions.familiarity[DP_MDC],"young player learns faster");int before=close.positions.familiarity[DP_MDC];learnPosition(close,DP_MDC,0);check(close.positions.familiarity[DP_MDC]==before,"no minutes no progression");learnPosition(close,DP_MDC,10000000,9);check(close.positions.familiarity[DP_MDC]<=100,"large input bounded");
 Player box=mid;box.pass=box.tackle=box.stamina=box.speed=40;int low=roleAptitude(box,DP_MC,1);box.stamina=95;box.speed=95;check(roleAptitude(box,DP_MC,1)>low,"box aptitude calculated from real attributes");
 auto m=std::make_unique<Match>();MatchSetup setup;setup.home=a;setup.away=b;setup.formation[0]=1;setup.formation[1]=1;setup.side[0]=0;setup.rules=RULESET_CAREER;auto& T=g_world.teams[a];T.tactical.customized=1;for(int s=0;s<11;s++)T.tactical.slot[s]=SlotTactic();T.tactical.slot[9].role=5;m->init(setup);m->ball.pos=m->fromTeamFrame(0,.58f,.5f);m->possTeam=0;
 for(int i=11;i<22;i++)m->pl[i].pos=m->fromTeamFrame(0,.97f,.5f);
 V2 false9,normal;m->formationTarget(9,false9);T.tactical.slot[9].role=0;m->setFormation(0,1);m->formationTarget(9,normal);check(m->progress(0,false9)<m->progress(0,normal)-.05f,"false nine physically drops towards midfield");
 T.tactical.slot[2].role=2;m->setFormation(0,1);V2 cover,stop;m->formationTarget(2,cover);T.tactical.slot[2].role=1;m->setFormation(0,1);m->formationTarget(2,stop);check(m->progress(0,cover)<m->progress(0,stop),"cover lower than stopper");check(m->pl[2].effects.press>1,"stopper presses more");
 T.tactical.slot[8].role=2;m->setFormation(0,1);V2 inside,wide;m->formationTarget(8,inside);T.tactical.slot[8].role=0;m->setFormation(0,1);m->formationTarget(8,wide);check(std::abs(inside.x-PITCH_W/2)<std::abs(wide.x-PITCH_W/2),"inside winger occupies central lane");
 T.tactical.slot[8].instructions=1u<<TI_SHOOT;m->setFormation(0,1);check(m->pl[8].effects.shot>1,"individual shooting instruction reaches physical engine");
 // Simple mode must produce exactly the same targets and attributes despite changing advanced metadata.
 T.tactical.slot[9].position=DP_SA;m->setFormation(0,1);check(m->pl[9].detailedPosition==DP_SA,"second attacker slot can be selected separately from natural position");
 setup.rules=RULESET_SIMPLE;m->init(setup);check(m->pl[9].detailedPosition==DP_BU,"simple ignores detailed slot overrides");m->ball.pos=m->fromTeamFrame(0,.6f,.5f);m->possTeam=0;V2 simpleA,simpleB;m->formationTarget(8,simpleA);float speed=m->pl[8].speed,pass=m->pl[8].pass;T.tactical.slot[8].role=2;T.tactical.slot[8].duty=DUTY_ATTACK;T.tactical.slot[8].instructions=(1u<<TI_INSIDE)|(1u<<TI_PRESS);for(auto& p:T.squad){initPositions(p);for(auto& fit:p.positions.familiarity)fit=0;p.morale=0;}m->init(setup);m->ball.pos=m->fromTeamFrame(0,.6f,.5f);m->possTeam=0;m->formationTarget(8,simpleB);check((simpleA-simpleB).len()<.0001f,"simple ignores roles duties instructions");check(std::abs(m->pl[8].speed-speed)<.0001f&&std::abs(m->pl[8].pass-pass)<.0001f,"simple ignores familiarity and morale");
 setup.rules=RULESET_CAREER;m->init(setup);check(m->pl[8].pass<pass,"career unfamiliar placement affects execution");
 T.squad[0].positions.target=DP_GB;T.squad[0].positions.familiarity[DP_GB]=85;T.squad[0].positions.practice[DP_GB]=123;T.squad[0].positions.developmentRole=1;T.tactical.slot[8].markPid=g_world.teams[b].squad[2].id;check(g_career.save("build/test-build4.sav"),"save position and tactic state");check(g_career.load("build/test-build4.sav"),"reload position and tactic state");check(g_world.teams[a].tactical.slot[8].markPid==g_world.teams[b].squad[2].id,"individual marking persisted");check(g_world.teams[a].squad[0].positions.target==DP_GB&&g_world.teams[a].squad[0].positions.practice[DP_GB]==123&&g_world.teams[a].squad[0].positions.developmentRole==1,"learning target and accumulated credit persisted");
 auto& keeper=g_world.teams[a].squad[0];int knowledge=keeper.positions.familiarity[DP_GB]*360+keeper.positions.practice[DP_GB];g_career.trainingMonth();check(keeper.positions.familiarity[DP_GB]*360+keeper.positions.practice[DP_GB]>knowledge,"monthly training follows individual target");
 setup.rules=RULESET_CAREER;m->init(setup);m->ceremony=false;m->state=MS_PLAY;m->clock=0;for(int frame=0;frame<120;frame++)m->update(1.f/60);check(!m->positionMinutes.empty(),"physical match records position minutes");float minutes=0;for(auto& p:m->positionMinutes)minutes+=p.second;check(minutes>0&&minutes<=22*m->clock+.01f,"minutes bounded by actual game clock");
 // Compare simulation with identical seeds: advanced state must not influence quick matches.
 std::vector<std::pair<int,int>> scores;for(int seed=1;seed<=50;seed++){g_rng=Rng(seed);MatchRes r;r.home=a;r.away=b;simulateMatch(r,nullptr);scores.push_back({r.hg,r.ag});}
 for(auto& p:g_world.teams[a].squad){p.morale=100;for(auto& v:p.positions.familiarity)v=100;}for(auto& t:g_world.teams[a].tactical.slot){t.role=5;t.duty=DUTY_ATTACK;t.instructions=(1u<<TI_ADVANCE)|(1u<<TI_SHOOT);}
 for(int seed=1;seed<=50;seed++){g_rng=Rng(seed);MatchRes r;r.home=a;r.away=b;simulateMatch(r,nullptr);check(scores[seed-1]==std::make_pair((int)r.hg,(int)r.ag),"quick simulation ignores advanced tactical state");}
 for(auto& P:g_basePyramids)if(P.country=="BEL"){g_career.newClubCareer(P.pools[0].clubs[0],2026);break;}check(careerRules(),"career rules work outside France");
 printf("PASS build4 roles: %d checks\n",checks);return 0;
}
