// Réservoirs de prénoms / noms par culture pour la génération des effectifs
#include "data.h"

const NamePool NAME_POOLS[NUM_CULTURES] = {
    // CU_FR
    { "Lucas Hugo Théo Nathan Louis Enzo Mathis Tom Maxime Antoine Kylian Ousmane Adrien Julien Romain Kevin Florian Yann Bastien Clément Alexis Quentin Thomas Nicolas Jordan Dylan Mehdi Karim Sofiane Moussa Ibrahima Mamadou Rayan Samuel Benjamin Jérémy Loïc Anthony Valentin Warren",
      "Martin Bernard Dubois Durand Lefebvre Leroy Moreau Simon Laurent Michel Garcia David Bertrand Roux Vincent Fournier Morel Girard André Mercier Blanc Guerin Boyer Garnier Chevalier Francois Legrand Gauthier Perrin Robin Clement Morin Nicolas Henry Roussel Mathieu Gautier Masson Marchand Duval Denis Dumont Marie Lemaire Noel Meyer Dufour Meunier Brun Blanchard Giraud Joly Riviere Lucas Brunet Gaillard Barbier Arnaud Martinez Gerard Roche Renard Schmitt Roy Leroux Colin Vidal Caron Picard Roger Fabre Aubert Lemoine Renaud Dumas Lacroix Olivier Philippe Bourgeois Pierre Benoit Rey Leclerc Payet Rolland Leclercq Guillaume Lecomte Lopez Jean Dupuy Guillot Hubert Berger Carpentier Sanchez Dupuis Moulin Louis Deschamps Huet Vasseur Perez Boucher Fleury Royer Klein Jacquet Adam Paris Poirier Marty Aubry Guyot Carre Charles Renault Charpentier Menard Maillard Baron Bertin Bailly Herve Schneider Fernandez Le_Gall Collet Leger Bouvier Julien Prevost Millet Perrot Daniel Le_Roux Cousin Germain Breton Besson Langlois Remy Le_Goff Pelletier Leveque Perrier Leblanc Barre Lebrun Marchal Weber Mallet Hamon Boulanger Jacob Monnier Michaud Rodriguez Guichard Gillet Etienne Grondin Poulain Tessier Chevallier Collin Chauvin Da_Silva Bouchet Gay Lemaitre Benard Marechal Humbert Reynaud Antoine Hoarau Perret Barthelemy Cordier Pichon Lejeune Gilbert Lamy Delaunay Pasquier Carlier Laporte Diallo Traore Kone Camara Toure Diaby Sissoko Kante Mendy Sarr" },
    // CU_EN
    { "Harry Jack Oliver Charlie George James Jacob Thomas William Joshua Daniel Luke Ryan Callum Connor Jordan Kyle Aaron Lewis Declan Marcus Bukayo Mason Jude Phil Kieran Reece Trent Ben John Conor Jamie Dominic Cole Ollie Morgan Tyler Liam Sean Nathan",
      "Smith Jones Taylor Brown Williams Wilson Johnson Davies Robinson Wright Thompson Evans Walker White Roberts Green Hall Wood Jackson Clarke Hughes Edwards Harris Turner Martin Cooper Hill Ward Morris Moore Clark Lee King Baker Harrison Morgan Allen James Scott Phillips Watson Davis Parker Price Bennett Young Griffiths Mitchell Kelly Cook Carter Richardson Bailey Collins Bell Shaw Murphy Miller Cox Richards Khan Marshall Anderson Simpson Ellis Adams Wilkinson Foster Chapman Powell Webb Rogers Gray Mason Ali Hunt Hussain Campbell Matthews Owen Palmer Holmes Mills Barnes Knight Lloyd Butler Russell Barker Fisher Stevens Jenkins Murray Dixon Harvey Graham Pearson Ahmed Fletcher Walsh Kaur Gibson Howard Andrews Stewart Elliott Reynolds Saunders Payne Fox Ford Pearce Day Brooks West Lawrence Cole Atkinson Bradley Spencer Gill Dawson Ball Burton O'Brien Watts Rose Booth Perry Ryan Grant Wells Armstrong Francis Rees Hayes Hart Hudson Newman Barnett Gordon Kane Rice Foden Saka Bellingham Stones Maguire Walker Trippier Pickford Henderson Sterling Rashford Grealish Mount Chilwell Shaw Gomez" },
    // CU_ES
    { "Alejandro Pablo Daniel Álvaro Adrián David Javier Sergio Carlos Marcos Hugo Mario Diego Raúl Iker Unai Mikel Jon Rodrigo Pedro Dani Gerard Jordi Marc Pau Nico Ferran Fermín Lamine Aitor Ander Borja Íñigo Rubén Óscar Víctor Joan Isco Koke",
      "García González Rodríguez Fernández López Martínez Sánchez Pérez Gómez Martín Jiménez Ruiz Hernández Díaz Moreno Muñoz Álvarez Romero Alonso Gutiérrez Navarro Torres Domínguez Vázquez Ramos Gil Ramírez Serrano Blanco Molina Morales Suárez Ortega Delgado Castro Ortiz Rubio Marín Sanz Núñez Iglesias Medina Garrido Cortés Castillo Santos Lozano Guerrero Cano Prieto Méndez Cruz Calvo Gallego Vidal León Márquez Herrera Peña Flores Cabrera Campos Vega Fuentes Carrasco Diez Caballero Reyes Nieto Aguilar Pascual Santana Herrero Lorenzo Montero Hidalgo Giménez Ibáñez Ferrer Durán Santiago Benítez Mora Vicente Vargas Arias Carmona Crespo Román Pastor Soto Sáez Velasco Moya Soler Parra Esteban Bravo Gallardo Rojas Oyarzabal Zubimendi Merino Olmo Laporte Cucurella Carvajal Morata Pedri Gavi Yamal Williams Raya Simón Grimaldo Baena Ayoze" },
    // CU_PT
    { "João Rafael Diogo Bernardo Rúben Bruno Gonçalo Pedro Tiago Nuno André Ricardo Vitinha Francisco Rui Miguel Luís Hugo Fábio Renato Nélson Danilo Otávio Cristiano Martim Samuel Tomás Henrique Duarte Afonso",
      "Silva Santos Ferreira Pereira Oliveira Costa Rodrigues Martins Jesus Sousa Fernandes Gonçalves Gomes Lopes Marques Alves Almeida Ribeiro Pinto Carvalho Teixeira Moreira Correia Mendes Nunes Soares Vieira Monteiro Cardoso Rocha Neves Coelho Cruz Cunha Pires Ramos Reis Simões Antunes Matos Fonseca Morais Lima Macedo Freitas Leite Tavares Guerreiro Neto Dias Castro Faria Leão Palhinha Inácio Conceição Trincão Quenda Dalot Cancelo Semedo Veiga" },
    // CU_BR
    { "Gabriel Lucas Matheus Pedro Guilherme Gustavo Rafael Felipe Bruno Vinícius Rodrygo Neymar Raphinha Endrick Casemiro Thiago Marquinhos Éder Alisson Ederson Danilo Richarlison Antony Paquetá Wendell Savinho Igor Luiz André Estêvão João Caio Douglas Leandro Diego Fabinho Everton Renan Wesley Murilo",
      "Silva Santos Oliveira Souza Rodrigues Ferreira Alves Pereira Lima Gomes Costa Ribeiro Martins Carvalho Almeida Lopes Soares Fernandes Vieira Barbosa Rocha Dias Nascimento Andrade Moreira Nunes Marques Machado Mendes Freitas Cardoso Ramos Gonçalves Santana Teixeira Araújo Moraes Pinto Correia Batista Cavalcanti Monteiro Barros Campos Xavier Moura Reis Farias Miranda Cunha Fonseca Magalhães Guimarães Militão Bremer Magalhães Firmino Jesus Martinelli Arana Beraldo Casemiro Paquetá Brandão" },
    // CU_IT
    { "Francesco Alessandro Lorenzo Leonardo Mattia Andrea Gabriele Riccardo Tommaso Edoardo Federico Matteo Giuseppe Antonio Marco Davide Nicolò Sandro Gianluigi Giorgio Alessio Manuel Ciro Moise Destiny Raoul Samuele Pietro Luca Simone",
      "Rossi Russo Ferrari Esposito Bianchi Romano Colombo Ricci Marino Greco Bruno Gallo Conti De_Luca Mancini Costa Giordano Rizzo Lombardi Moretti Barbieri Fontana Santoro Mariani Rinaldi Caruso Ferrara Galli Martini Leone Longo Gentile Martinelli Vitale Lombardo Serra Coppola De_Santis D'Angelo Marchetti Parisi Villa Conte Ferraro Ferri Fabbri Bianco Marini Grasso Valentini Messina Sala De_Angelis Gatti Pellegrini Palumbo Sanna Farina Rizzi Monti Cattaneo Morelli Amato Silvestri Mazza Testa Grassi Pellegrino Carbone Giuliani Benedetti Barone Rossetti Caputo Montanari Guerra Palmieri Bernardi Martino Fiore De_Rosa Ferretti Bellini Basile Riva Donati Piras Vitali Battaglia Sartori Neri Costantini Milani Pagano Ruggiero Sorrentino D'Amico Orlando Damico Negri Barella Tonali Bastoni Chiesa Donnarumma Dimarco Frattesi Retegui Scamacca Calafiori" },
    // CU_DE
    { "Maximilian Alexander Paul Leon Lukas Luca Felix Jonas Tim David Elias Niklas Florian Kai Jamal Joshua Leroy Serge Thomas Manuel Toni Ilkay Marc-André Nico Robin Julian Timo Leonie Jonathan Aleksandar Benjamin Deniz Chris Karim Malick",
      "Müller Schmidt Schneider Fischer Weber Meyer Wagner Becker Schulz Hoffmann Schäfer Koch Bauer Richter Klein Wolf Schröder Neumann Schwarz Zimmermann Braun Krüger Hofmann Hartmann Lange Schmitt Werner Schmitz Krause Meier Lehmann Schmid Schulze Maier Köhler Herrmann König Walter Mayer Huber Kaiser Fuchs Peters Lang Scholz Möller Weiß Jung Hahn Schubert Vogel Friedrich Keller Günther Frank Berger Winkler Roth Beck Lorenz Baumann Franke Albrecht Schuster Simon Ludwig Böhm Winter Kraus Martin Schumacher Krämer Vogt Stein Jäger Otto Sommer Groß Seidel Heinrich Brandt Haas Schreiber Graf Schulte Dietrich Ziegler Kuhn Kühn Pohl Engel Horn Busch Bergmann Thomas Voigt Sauer Arnold Wolff Pfeiffer Kimmich Musiala Wirtz Havertz Rüdiger Tah Schlotterbeck Undav Beier Mittelstädt Raum Andrich Gnabry Sané Füllkrug Neuer Baumann Nübel" },
    // CU_NL
    { "Daan Sem Lucas Levi Finn Milan Jesse Bram Luuk Thijs Ruben Stijn Tijjani Cody Xavi Virgil Frenkie Matthijs Denzel Jeremie Joshua Donyell Teun Wout Quinten Micky Brian Jurriën Kees Joey",
      "de_Jong Jansen de_Vries van_den_Berg van_Dijk Bakker Janssen Visser Smit Meijer de_Boer Mulder de_Groot Bos Vos Peters Hendriks van_Leeuwen Dekker Brouwer de_Wit Dijkstra Smits de_Graaf van_der_Meer van_der_Linden Kok Jacobs de_Haan Vermeulen van_den_Heuvel van_der_Veen van_den_Broek de_Bruijn de_Bruin van_der_Heijden Schouten van_Beek Willems van_Vliet van_de_Ven Hoekstra Maas Verhoeven Koster van_Dam van_der_Wal Prins Blom Huisman Peeters Maes Claes Wouters Mertens Goossens Dubois Lambert Tielemans Doku Trossard Onana De_Ketelaere Openda Lukebakio Castagne Theate Debast Gakpo Reijnders Simons Frimpong Dumfries Malen Weghorst Verbruggen Timber Gravenberch Koopmeiners" },
    // CU_NORD
    { "Erling Martin Kristoffer Magnus Alexander Oscar Emil William Viktor Rasmus Christian Mathias Jonas Anders Joachim Andreas Morten Sander Pierre-Emile Kasper Gustav Hugo Isak Elias Ludvig Teemu Jere Joel Aron Rúnar",
      "Hansen Johansen Olsen Larsen Andersen Pedersen Nilsen Kristiansen Jensen Karlsen Johnsen Pettersen Eriksen Berg Haugen Hagen Johannessen Andreassen Jacobsen Dahl Jørgensen Halvorsen Henriksen Lund Sørensen Jakobsen Moen Gundersen Iversen Strand Solberg Svendsen Eide Knutsen Martinsen Paulsen Bakken Kristensen Mathisen Lie Christensen Rasmussen Madsen Nielsen Thomsen Poulsen Johansson Andersson Karlsson Nilsson Eriksson Larsson Olsson Persson Svensson Gustafsson Pettersson Jonsson Lindberg Lindström Lindqvist Lindgren Berglund Fredriksson Sandberg Henriksson Forsberg Sjöberg Wallin Engström Eklund Danielsson Lundqvist Håkansson Björk Virtanen Korhonen Mäkinen Nieminen Mäkelä Hämäläinen Laine Heikkinen Koskinen Järvinen Haaland Ødegaard Sørloth Nusa Højlund Hjulmand Gyökeres Kulusevski Isak Sigurdsson" },
    // CU_SLAV
    { "Robert Piotr Jakub Kamil Mateusz Krzysztof Dmitri Aleksandr Sergei Ivan Andrei Mikhail Oleksandr Artem Mykola Tomáš Patrik Adam Ondřej Vladimir Pavel Nikita Yuri Viktor Denys Georgi Khvicha Giorgi Stanislav Milan",
      "Nowak Kowalski Wiśniewski Wójcik Kowalczyk Kamiński Lewandowski Zieliński Szymański Woźniak Dąbrowski Kozłowski Jankowski Mazur Kwiatkowski Krawczyk Piotrowski Grabowski Nowakowski Pawłowski Michalski Nowicki Adamczyk Dudek Zając Wieczorek Jabłoński Król Majewski Olszewski Ivanov Smirnov Kuznetsov Popov Vasiliev Petrov Sokolov Mikhailov Novikov Fedorov Morozov Volkov Alekseev Lebedev Semenov Egorov Pavlov Kozlov Stepanov Nikolaev Orlov Andreev Makarov Zakharov Zaitsev Solovyov Borisov Yakovlev Grigoriev Romanov Shevchenko Kovalenko Bondarenko Tkachenko Kravchenko Oliynyk Shevchuk Polishchuk Boyko Tkachuk Moroz Lysenko Rudenko Savchenko Petrenko Novák Svoboda Novotný Dvořák Černý Procházka Kučera Veselý Horák Němec Pokorný Marek Pospíšil Hájek Král Jelínek Růžička Beneš Fiala Sedláček Doležal Zeman Kolář Navrátil Čermák Kvaratskhelia Mikautadze Mamardashvili Zinchenko Mudryk Dovbyk Tsygankov Schick Souček Szczęsny Zieliński Kiwior" },
    // CU_BALK
    { "Luka Marko Ivan Josip Mateo Nikola Stefan Dušan Aleksandar Dejan Andrej Filip Mario Ante Domagoj Mislav Joško Lovro Petar Sergej Milan Nemanja Edin Miralem Armin Kristjan Arber Granit Ardian Adem",
      "Horvat Kovačević Babić Marić Jurić Novak Kovačić Knežević Vuković Marković Petrović Pavlović Perić Tomić Božić Matić Radić Grgić Vidović Šimić Nikolić Jovanović Đorđević Ilić Stanković Stojanović Popović Kostić Mitrović Živković Milošević Todorović Savić Obradović Lazić Janković Ristić Vlahović Mitrović Tadić Milinković Lukić Gudelj Pavlović Hodžić Begović Hasanović Kurtić Džeko Pjanić Demirović Kolašinac Hoxha Berisha Krasniqi Gashi Shala Morina Bajrami Rrahmani Xhaka Shaqiri Muriqi Broja Asllani Ramadani Gvardiol Modrić Kramarić Perišić Brozović Livaković Sučić Baturina Budimir Stanišić Šutalo Ionescu Popescu Stan Dumitru Munteanu Mureşan Drăguşin Hagi Man Mihăilă Radu Niţă Sorescu Racovitan" },
    // CU_TR
    { "Arda Kerem Hakan Cengiz Burak Emre Mert Yusuf Ferdi Kaan Orkun Barış İsmail Salih Zeki Kenan Semih Oğuz Abdülkerim Merih Uğurcan Altay Cenk Enes Samet Ozan Can Eren Berkan Umut",
      "Yılmaz Kaya Demir Şahin Çelik Yıldız Yıldırım Öztürk Aydın Özdemir Arslan Doğan Kılıç Aslan Çetin Kara Koç Kurt Özkan Şimşek Polat Özcan Korkmaz Çakır Erdoğan Yavuz Can Acar Şen Aktaş Güler Yalçın Güneş Bozkurt Bulut Keskin Ünal Turan Gül Özer Işık Kaplan Avcı Sarı Tekin Taş Köse Yüksel Ateş Aksoy Güler Kökçü Çalhanoğlu Akgün Bardakcı Yıldız Kahveci Ayhan Kadıoğlu Aktürkoğlu Müldür Tosun Ünder Demiral Söyüncü Kabak" },
    // CU_ARAB
    { "Mohamed Ahmed Youssef Omar Ali Hakim Achraf Sofiane Riyad Ismaël Karim Walid Hamza Anas Bilal Saïd Nabil Amine Yassine Mehdi Salem Abdallah Khalid Faisal Firas Mahmoud Ibrahim Hussein Ayoub Ilias",
      "Benali Haddad Mansour Saleh Nasser Hassan Ibrahim Khalil Mahmoud Youssef Rahman Aziz Karim Hamdi Farouk Salah Zaki Ghanem Bakr Suleiman Othman Amrani Benyahia Bensaïd Belkacem Boudjema Mahrez Bennacer Aouar Feghouli Atal Benrahma Slimani Belaïli Ounahi Amrabat Ziyech Hakimi En-Nesyri Mazraoui Aguerd Saïss Bounou Diaz Brahimi Boufal Msakni Khazri Skhiri Laïdouni Talbi Mejbri Trezeguet Marmoush Elneny Hegazy Kahraba Alaa Dawsari Shahri Bulaihi Kanno Afif Almoez Hatem Tamari Naimat Hindi Mabkhout Harbi Fares Obeid Sayed Hussein Naser" },
    // CU_AFW
    { "Moussa Ibrahima Mamadou Cheikh Sadio Idrissa Kalidou Ismaïla Seko Amadou Boubacar Souleymane Yves Franck Wilfried Serge Sébastien Nicolas Pape Lamine Oumar Bamba Hamari Simon Jean-Philippe Christian Eric Didier Salomon Vincent",
      "Diallo Traoré Koné Camara Touré Diarra Coulibaly Cissé Keïta Sanogo Sylla Sangaré Doumbia Kouyaté Diop Ndiaye Fall Sow Gueye Mendy Seck Sarr Niang Faye Ba Diagne Mbaye Badji Dieng Kouassi Kouamé Konan Yao N'Guessan Bamba Zaha Haller Kessié Fofana Seri Aurier Boly Onana Anguissa Mbeumo Aboubakar Choupo-Moting Toko-Ekambi Nkoudou Ngamaleu Bakambu Mbemba Wissa Kakuta Bolasie Tisserand Aubameyang Lemina Bouanga Ecuele Bertrand Traoré Dembélé Tchouaméni Kolo Hountondji Dossou Mounié Adilehou Sessègnon Bamogo Bayala Kaboré Tapsoba Zongo" },
    // CU_AFE
    { "Kwame Kofi Emmanuel Samuel Victor Wilfred Alex Joshua Ademola Kelechi Ahmed Moses Mohammed Thomas Jordan André Inaki Antoine Percy Themba Teboho Lyle Ronwen Bongani Patson Ashley Oghenekaro Calvin Frank Divine",
      "Mensah Owusu Boateng Asamoah Appiah Addo Osei Adjei Ofori Agyemang Amartey Ayew Partey Kudus Semenyo Djiku Salisu Osimhen Lookman Iwobi Ndidi Chukwueze Onyeka Aina Simon Bassey Ekong Troost-Ekong Nwabali Moffi Iheanacho Uzoho Awoniyi Ogbu Okoye Onuachu Dessers Chukwu Nwosu Obi Okafor Adeyemi Balogun Adeleke Olatunji Mokoena Zwane Tau Foster Mofokeng Mudau Williams Rayners Appollis Sithole Hlongwane Musona Billiat Daka Mwepu Sakala Kangwa Chama Kalaba Olunga Wanyama Mariga Otieno Omondi Kiprotich Mutua Wanjala Okello Onyango" },
    // CU_JP
    { "Takumi Kaoru Wataru Daichi Takefusa Ritsu Junya Ko Hiroki Shogo Yuki Ayase Kyogo Keito Takehiro Zion Kou Hidemasa Reo Ao Yuto Kento Sota Haruki Shunsuke Takuma Yuya Kaishu Keisuke Tomoya",
      "Sato Suzuki Takahashi Tanaka Watanabe Ito Yamamoto Nakamura Kobayashi Kato Yoshida Yamada Sasaki Yamaguchi Matsumoto Inoue Kimura Hayashi Shimizu Yamazaki Mori Abe Ikeda Hashimoto Yamashita Ishikawa Nakajima Maeda Fujita Ogawa Goto Okada Hasegawa Murakami Kondo Ishii Saito Sakamoto Endo Aoki Fujii Nishimura Fukuda Ota Miura Minamino Mitoma Kubo Doan Tomiyasu Itakura Morita Ueda Furuhashi Suzuki Machida Nakamura Ito Sugawara Hatate Maeda Tanaka" },
    // CU_KR
    { "Heung-min Min-jae Kang-in Hee-chan Jae-sung Gue-sung Woo-yeong In-beom Seung-ho Young-woo Jin-su Hyeon-gyu Ji-sung Tae-hwan Dong-gyeong Chang-hoon Seung-gyu Hyun-woo Jun-ho Kyung-won Yong-woo Sang-ho Won-sang Moon-hwan Jin-seob",
      "Kim Lee Park Choi Jung Kang Cho Yoon Jang Lim Han Oh Seo Shin Kwon Hwang Ahn Song Jeon Hong Yoo Ko Moon Yang Son Bae Baek Heo Nam Sim Noh Ha Kwak Sung Cha Joo Woo Koo Min Ryu Na Jin Ji Eom Byun" },
    // CU_CN
    { "Wei Lei Jun Hao Yang Tao Bin Chao Peng Jian Yong Qiang Feng Long Xin Ming Yi Kai Zhen Rui Xiang Chen Jie Bo Liang Hui Tian Yu Wu Shuai",
      "Wang Li Zhang Liu Chen Yang Huang Zhao Wu Zhou Xu Sun Ma Zhu Hu Guo He Gao Lin Luo Zheng Liang Xie Song Tang Han Feng Deng Cao Peng Zeng Xiao Tian Dong Pan Yuan Cai Jiang Yu Du Ye Cheng Wei Su Lu Ding Ren Shen Yao Lu Jiang Cui Zhong Tan Lu Fan Wang Liao Shi Jin Wei Jia Xia Fu Fang Zou Xiong Bai Meng Qin Qiu Hou Jiang Yin Xue Yan Duan Lei Long Li Shi Tao He Mao Hao Gu Gong Shao Wan Qin Wu Qian Dai Yan Ou Mo Kong Xiang Chang" },
    // CU_LATAM
    { "Lionel Ángel Rodrigo Julián Lautaro Enzo Alexis Emiliano Nicolás Cristian Giovani Nahuel Leandro Luis Federico Darwin Ronald José Manuel Santiago Jhon Richard Moisés Piero Edson Raúl Hirving Guillermo Santiago Kendry",
      "González Rodríguez Gómez Fernández López Díaz Martínez Pérez García Sánchez Romero Sosa Álvarez Torres Ruiz Ramírez Flores Acosta Benítez Medina Suárez Herrera Aguirre Pereyra Gutiérrez Giménez Molina Silva Castro Rojas Ortiz Núñez Luna Juárez Cabrera Ríos Ferreyra Godoy Morales Domínguez Moreno Peralta Vega Carrizo Quiroga Castillo Ledesma Muñoz Ojeda Ponce Vera Vázquez Villalba Cardozo Navarro Coronel Vargas Paz Montiel Otamendi Martínez De_Paul Mac_Allister Messi Di_María Tagliafico Molina Romero Paredes Almada Garnacho Nuñez Valverde Bentancur Ugarte Araújo Olivera Viña Arrascaeta Pellistri Caicedo Hincapié Plata Estupiñán Valencia Arboleda Borré Sinisterra Muñoz Lucumí Mina Díaz Arias Lozano Jiménez Álvarez Chávez Montes Vásquez Edson Sánchez Gallardo Ochoa Malagón Rangel" },
    // CU_PERS
    { "Mehdi Sardar Alireza Saman Karim Ali Morteza Saeid Milad Hossein Ramin Majid Omid Amir Reza Eldor Abbosbek Jaloliddin Otabek Khojimat Oston Abdukodir Rustam Parviz Shohrukh Farrukh Timur Dilshod Sherzod Azizbek",
      "Taremi Azmoun Jahanbakhsh Ghoddos Beiranvand Hosseini Pouraliganji Kanaanizadegan Mohammadi Karimi Ezatolahi Nourollahi Gholizadeh Rezaeian Moharrami Torabi Ansarifard Shojaei Hajsafi Ghasemi Rahimi Ahmadi Hosseinzadeh Rezaei Jafari Sadeghi Mousavi Ghorbani Heidari Kazemi Shomurodov Fayzullaev Masharipov Urunov Khusanov Mozgovoy Khamrobekov Alikulov Nasrullaev Ashurmatov Erkinov Sayfiev Abdullaev Rakhmonov Tursunov Nazarov Karimov Yusupov" },
    // CU_SEA
    { "Nguyen Tuan Quang Van Duc Minh Thanh Hai Chanathip Teerasil Supachok Suphanat Theerathon Egy Witan Pratama Asnawi Marselino Jordi Safawi Faisal Arif Ikhsan Hariss Irfan Aung Kyaw Myat Stephan Neil",
      "Nguyen Tran Le Pham Hoang Phan Vu Dang Bui Do Ho Ngo Duong Ly Songkrasin Dangda Sarachat Mueanta Bunmathan Kaewprom Maulana Arhan Ferdinan Rizky Ridho Hubner Idzes Walsh Rasid Halim Corbin-Ong Ramli Radzi Mahmud Abdullah Ismail Hassan Rahman Hussain Nyein Min Soe Oo Win Htet Tun Schrock Etheridge Reichelt Patiño" },
    // CU_IND
    { "Sunil Sandesh Gurpreet Anirudh Sahal Lallianzuala Brandon Liston Manvir Rahul Akash Jeakson Nikhil Anwar Subhasish Jamal Tariq Saad Kamal Imran Arjun Vikram Rohit Amit Rajesh Suresh Aman Ravi Hamza Pradeep",
      "Chhetri Jhingan Sandhu Thapa Samad Chhangte Fernandes Colaco Singh Bheke Mishra Kumar Sharma Patel Gupta Das Bose Roy Reddy Nair Menon Iyer Khan Ali Hussain Ahmed Rahman Chowdhury Islam Hossain Miah Uddin Siddique Karim Tamang Gurung Rai Magar Shrestha Lama Perera Fernando Silva De_Silva Jayasuriya Wickramasinghe Dorji Wangchuk" },
    // CU_PAC
    { "Chris Winston Ryan Michael Joe Tim Marko Clayton Liberato Roy Sione Semi Tevita Viliami Iosefa Etonia Ratu Kaiwai Micah Nathan Kosta Elijah Matt Alex Callum Ben Liam Joel Tyler Jesse",
      "Wood Reid Thomas Boxall Barbarouses Cacace Tuiloma Payne Singh Stamenic Just Garbett Bell Crocombe Gleeson Waine Rufer Old Vaka Tuilagi Fifita Taufa Tupou Latu Havili Fonua Mata'afa Pouono Leota Faleolo Ravuama Naidu Krishna Dunadamu Kumar Tamanisau Wasasala Kakala Toara Nakoro Dinh Tehau Vahirua Bourebare Kali Lolo Kauhalu Totori Bina" },
    // CU_GR
    { "Giorgos Konstantinos Dimitris Nikos Vangelis Kostas Anastasios Christos Petros Tasos Giannis Manolis Sokratis Odysseas Fotis Vasilis Pantelis Thanasis Andreas Lazaros",
      "Papadopoulos Papadakis Georgiou Nikolaou Konstantinou Pappas Oikonomou Vlachos Makris Dimitriou Ioannou Karagiannis Antoniou Christodoulou Anastasiou Mavropanos Tzolis Masouras Bakasetas Pelkas Pavlidis Giakoumakis Tsimikas Vlachodimos Mantalos Siopis Kourbelis Retsos Zeca Kyriakopoulos Douvikas Ioannidis Hatzidiakos Konstantelias Vagiannidis Koulierakis Christodoulopoulos" },
    // CU_HU
    { "Dominik Péter Ádám Roland Milos Willi Loïc Attila Bendegúz Kevin Zsolt Barnabás Dénes Márton Zalán Botond Balázs Gábor László Martin",
      "Szoboszlai Gulácsi Sallai Szalai Kerkez Orbán Nagy Kovács Tóth Szabó Horváth Varga Kiss Molnár Németh Farkas Balogh Papp Takács Juhász Lakatos Mészáros Oláh Simon Rácz Fekete Schäfer Styles Lang Fiola Dárdai Bolla Varga Kleinheisler Botka Csoboth Gazdag" },
};
