#include "game.h"
#include "serial.h"
#include <cstring>
#include <set>
#include <limits>
#include <cmath>
template<size_t N> static void textTo(char (&d)[N],const std::string& s){snprintf(d,N,"%s",s.c_str());}
const char* directorDomainName(int i){static const char* n[]={"Recherche de joueurs","Présélection des recrues","Offres de transfert","Indemnités de transfert","Contrats des recrues","Prolongations des joueurs","Ventes","Liste des transferts","Prêts entrants","Prêts sortants","Clubs pour les prêts","Contacts / négociations","Recrutement des jeunes","Arrivées du staff","Renouvellement du staff"};return n[std::clamp(i,0,DD_COUNT-1)];}
const char* directorModeName(int i){static const char* n[]={"Manuel","Conseil","Négociation","Complète"};return n[std::clamp(i,0,3)];}
const char* directorSkillName(int i){static const char* n[]={"Recrutement","Négociation","Vente","Contrats","Prêts","Marché","Réseau national","Réseau international","Détection des jeunes","Analyse de l'effectif","Relations / contacts","Gestion du staff"};return n[std::clamp(i,0,DK_COUNT-1)];}
const char* directorPhilosophyName(int i){static const char* n[]={"Privilégier les jeunes","Joueurs confirmés","Recrutement local","Recrutement national","Recrutement international","Joueurs libres","Acheter pour revendre","Conserver les cadres","Limiter les salaires","Centre de formation","Joueurs polyvalents","Adaptation à la tactique"};return n[std::clamp(i,0,DPH_COUNT-1)];}
const char* directorStatusName(int i){static const char* n[]={"Intouchable","Important","Rotation","Disponible","À vendre","À prêter"};return n[std::clamp(i,0,5)];}
const char* directorPhaseName(int i){static const char* n[]={"Préparation","Offre au club","Contrat du joueur","Validation humaine","Terminé","Abandonné","En pause","Annulé"};return n[std::clamp(i,0,7)];}
bool Career::directorEnabled()const{return kind==CK_CLUB&&!opts.lite&&!euroOnly&&!life.isPlayer&&userTeam>=0&&userTeam<(int)g_world.teams.size()&&mgr.managerMode&&!mgr.sacked&&(!sportingMode()||sporting.employed);}
static StaffMember* member(Career& K){for(auto& s:K.mgr.staff)if(s.role==SR_DIRECTOR)return &s;return nullptr;}
static int64_t staffWages(const Career& K){int64_t w=0;for(auto& s:K.mgr.staff)w+=s.wage;return w;}
static void note(Career& K,const std::string& s){K.season.news.push_back("[Directeur sportif] "+s);}
void Career::directorSync(){if(!directorEnabled())return;
 if(director.club!=userTeam){director=DirectorState();director.club=userTeam;director.rng=hashStr(g_world.teams[userTeam].name)^0xD1AEC70;}
 auto& D=director;const Team& U=g_world.teams[userTeam];
 if(D.policyYear!=year){D.policyYear=year;D.limits.budgetBase=std::max<int64_t>(0,mgr.budget);D.limits.used=0;D.limits.boardFees=D.limits.budgetBase*80/100;int64_t payroll=wageBill(userTeam)+staffWages(*this);D.limits.boardWages=payroll*120/100+std::max<int64_t>(0,mgr.incomeBase)/10;if(!D.limits.configured)D.limits.wageCap=D.limits.boardWages;
  if(!D.limits.configured)D.limits.maxFee=U.status==CS_AMATEUR?0:(int)std::min<int64_t>(1000000,std::max<int64_t>(1,D.limits.budgetBase/4));
  if(!D.limits.configured&&U.status!=CS_AMATEUR){int max=1;for(auto& p:U.squad)max=std::max(max,playerWage(p));D.limits.maxWage=std::min(1000000,max*3/2);}
  D.limits.configured=1;D.loanTerms.erase(std::remove_if(D.loanTerms.begin(),D.loanTerms.end(),[&](auto l){return l.year<year;}),D.loanTerms.end());D.targets.clear();D.needs.clear();D.contracts.clear();D.lastResearch=-100;D.lastTick=-100;
  D.negotiations.erase(std::remove_if(D.negotiations.begin(),D.negotiations.end(),[](const DirectorNegotiation& n){return n.phase==DN_DONE||n.phase==DN_FAILED||n.phase==DN_CANCELLED;}),D.negotiations.end());
  for(auto& n:D.negotiations){n.phase=DN_CANCELLED;textTo(n.message,"Dossier clos à l'intersaison.");}
 }
 if(D.staffYear&&D.staffYear<year){int elapsed=year-D.staffYear;for(auto& c:D.staffContracts){if(sportingMode()&&c.role==SR_DIRECTOR){c.years=sporting.contractYears;continue;}c.years=std::max(0,c.years-elapsed);if(c.years==0&&D.mode[DD_STAFF_RENEW]==DM_AUTO)c.years=3;}
  if(D.profile.name[0]){D.profile.age+=elapsed;D.profile.experience+=elapsed;D.profile.years=std::max(0,D.profile.years-elapsed);if(D.profile.years==0&&D.mode[DD_STAFF_RENEW]==DM_AUTO){D.profile.years=3;note(*this,"Contrat du directeur sportif renouvelé.");}}
  for(auto& c:D.staffContracts)if(!c.years)mgr.staff.erase(std::remove_if(mgr.staff.begin(),mgr.staff.end(),[&](const StaffMember& s){return s.role==c.role&&std::string(s.name)==c.name;}),mgr.staff.end());
 }
 D.staffYear=year;
 D.staffContracts.erase(std::remove_if(D.staffContracts.begin(),D.staffContracts.end(),[&](auto c){for(auto& s:mgr.staff)if(s.role==c.role&&std::string(c.name)==s.name)return false;return true;}),D.staffContracts.end());
 for(auto& s:mgr.staff){bool known=false;for(auto& c:D.staffContracts)if(c.role==s.role&&std::string(c.name)==s.name){known=true;break;}if(!known){DirectorStaffContract c;c.role=s.role;textTo(c.name,s.name);D.staffContracts.push_back(c);}}
 auto* s=member(*this);if(!s){D.profile=DirectorProfile();return;}
 if(sportingMode()){auto& H=sporting.profile;D.profile=DirectorProfile();textTo(D.profile.name,std::string(H.first)+" "+H.last);D.profile.age=H.age;D.profile.nation=H.nation;D.profile.wage=sporting.wage;D.profile.years=sporting.contractYears;D.profile.reputation=H.reputation;D.profile.experience=H.experience;D.profile.level=s->level;D.profile.philosophy=H.philosophy;for(int k=0;k<DK_COUNT;k++)D.profile.skill[k]=H.skills[k];return;}
 if(std::string(D.profile.name)!=s->name||D.profile.level!=s->level){DirectorProfile P;P.level=s->level;P.age=s->age;P.nation=U.nation;P.experience=std::max(1,s->age-30);P.reputation=std::min(99,10+s->level*16);P.wage=s->wage;P.years=3;textTo(P.name,s->name);Rng r(hashStr(s->name)^(uint64_t)(userTeam*991+s->level));for(auto& skill:P.skill)skill=(uint8_t)std::clamp(s->level*16+r.range(-7,13),10,99);P.philosophy=U.status==CS_AMATEUR?DP_LOCAL:(uint8_t)r.range(0,DPH_COUNT-1);D.profile=P;}
 D.profile.wage=s->wage;s->age=D.profile.age;
}
static bool compatible(const Team& U,const Player& p){return (p.gender==1)==(U.youth==6);}
static int countAt(const Team& T,int position,bool available=true){int n=0;for(auto& p:T.squad)if((!available||p.injured<=0&&p.suspended<=0)&&positionFamiliarity(p,position)>=60)n++;return n;}
int Career::directorTargetScore(const Player& p,int club,int position)const{
 const auto& D=director;const auto& U=g_world.teams[userTeam];const auto& T=g_world.teams[club];int fit=positionFamiliarity(p,position),price=T.freeAgents||T.parent==userTeam?0:p.value();int wage=U.status==CS_AMATEUR?0:wageDemand(p,userTeam);int score=fit+p.overall()*2+std::max(0,(int)p.pot-p.overall())*D.profile.skill[DK_YOUTH]/50;
 score+=fit*D.profile.skill[DK_RECRUIT]/200;if(D.request.role>=0)score+=roleAptitude(p,position,D.request.role)/2;int style=D.request.profile>=0?D.request.profile:D.profile.philosophy;score-=std::min(90,price*60/std::max(1,D.limits.maxFee));score-=std::min(60,wage*40/std::max(1,D.limits.maxWage));score+=T.nation==U.nation?D.profile.skill[DK_NATIONAL]/5:D.profile.skill[DK_INTERNATIONAL]/5;score+=std::max(-40,std::min(25,teamReputation(userTeam)-p.overall()));
 switch(style){case DP_YOUNG:score+=(25-p.age)*5+std::max(0,(int)p.pot-p.overall());break;case DP_EXPERIENCED:score+=p.overall()+std::min(20,(int)p.age-22)*2;break;case DP_LOCAL:score+=T.district==U.district&&U.district>=0?55:T.region==U.region&&U.region>=0?25:0;break;case DP_NATIONAL:score+=T.nation==U.nation?35:-35;break;case DP_INTERNATIONAL:score+=p.nation!=U.nation?35:0;break;case DP_FREE:score+=price==0?75:-25;break;case DP_TRADING:score+=std::max(0,(int)p.pot-p.overall())*3+(24-p.age)*4;break;case DP_KEEP:score+=T.parent==userTeam?80:-20;break;case DP_LOW_WAGE:score-=wage*80/std::max(1,D.limits.maxWage);break;case DP_ACADEMY:score+=T.parent==userTeam?100:p.age<=20?30:-20;break;case DP_VERSATILE:for(auto f:p.positions.familiarity)if(f>=60)score+=12;break;case DP_TACTICAL:score+=fit+roleAptitude(p,position,D.request.role>=0?D.request.role:0);break;}
 if(sportingMode()){auto& policy=sporting.policy;score-=std::abs((int)p.age-policy.averageAge)*2;score+=p.age<=21?policy.youth/3:0;score+=T.nation==U.nation?policy.local/4:0;int old=0;for(auto& q:U.squad)old+=q.age>30;if(p.age>30&&old>=policy.over30)score-=80;for(auto& n:sporting.network)if(n.nation==T.nation)score+=n.knowledge/5;score-=wage*policy.wages*10/std::max(1,D.limits.maxWage);}
 score+=personalityRecruitScore(*this,p,style);
 return score;
}
bool Career::directorCanSpend(int fee,int wage,std::string& reason,int oldWage)const{
 const auto& D=director;const auto& L=D.limits;if(!directorEnabled()||!D.profile.name[0]){reason="Directeur sportif indisponible.";return false;}
 if(fee<0||wage<0||fee>mgr.budget||fee>std::max<int64_t>(0,std::min(L.boardFees,L.budgetBase*L.budgetPct/100)-L.used)){reason="Enveloppe sportive ou budget disponible dépassé.";return false;}
 if(wage>L.maxWage){reason="Salaire individuel maximum dépassé.";return false;}
 int64_t cap=std::min(L.wageCap,L.boardWages);if(hasDncg()&&mgr.wageCapK>0)cap=std::min(cap,mgr.wageCapK);
 if(wageBill(userTeam)+staffWages(*this)-oldWage+wage>cap){reason="Plafond annuel des salaires dépassé.";return false;}
 if(hasDncg()&&mgr.dncg&&fee>0){reason="DNCG : recrutement payant interdit.";return false;}return true;
}
bool Career::directorProtected(int pid)const{
 for(auto& p:director.policies)if(p.pid==pid){if(p.noSell||p.status==DS_UNTOUCHABLE||p.status==DS_IMPORTANT)return true;if(p.status==DS_FOR_SALE||p.status==DS_FOR_LOAN)return false;}
 const auto& U=g_world.teams[userTeam];if(pid==U.captainPid||pid==U.vicePid)return true;auto xi=g_world.pickLineup(userTeam,U.formation,RULESET_CAREER);for(int k=0;k<11&&k<(int)xi.size();k++)if(xi[k]>=0&&U.squad[xi[k]].id==pid)return true;return false;
}
void Career::directorPolicy(int pid,int status,bool locked){int i;if(g_world.findPlayer(pid,&i)!=userTeam)return;for(auto& p:director.policies)if(p.pid==pid){p.status=std::clamp(status,0,5);p.noSell=locked;return;}DirectorPlayerPolicy p;p.pid=pid;p.status=std::clamp(status,0,5);p.noSell=locked;director.policies.push_back(p);}
void Career::directorAnalyse(bool research){directorSync();if(!directorEnabled()||!director.profile.name[0])return;auto& D=director;const auto& U=g_world.teams[userTeam];D.needs.clear();D.contracts.clear();D.report.clear();int wanted[DP_COUNT]={};for(int s=0;s<11;s++)wanted[teamSlotPosition(U,U.formation,s)]++;
 for(int pos=0;pos<DP_COUNT;pos++)if(wanted[pos]||D.request.position==pos){DirectorNeed n;n.position=pos;n.required=std::max(1,wanted[pos])+1;n.available=countAt(U,pos);for(auto& T:g_world.teams)if(T.parent==userTeam&&T.squadGen)for(auto& p:T.squad)if(p.age>=16&&p.injured<5&&positionFamiliarity(p,pos)>=65)n.academy++;
 int expiring=0,old=0;for(auto& p:U.squad)if(positionFamiliarity(p,pos)>=60){expiring+=p.contract!=2&&contractYears(p)<=1;old+=p.age>=32;}
 n.priority=n.available<wanted[pos]?120:n.available<n.required?75:expiring?35+D.profile.skill[DK_ANALYSIS]/5:old?15+D.profile.skill[DK_ANALYSIS]/5:0;if(n.academy&&n.priority==75)n.priority=std::max(30,n.priority-D.profile.skill[DK_ANALYSIS]/2);if(D.request.position==pos)n.priority=140;std::string why=n.available<wanted[pos]?"Poste titulaire insuffisamment couvert":n.available<n.required?"Doublure / rotation nécessaire":expiring?"Contrat court à ce poste":old?"Préparer la relève":"Poste déjà couvert";textTo(n.reason,why+fmt(" (%d disponibles, %d jeunes / réserves)",n.available,n.academy));D.needs.push_back(n);}
 std::stable_sort(D.needs.begin(),D.needs.end(),[](auto a,auto b){return a.priority>b.priority;});
 for(auto& p:U.squad)if(p.contract!=2&&contractYears(p)<=1&&std::none_of(loans.begin(),loans.end(),[&](auto l){return l.pid==p.id&&l.to==userTeam;})){DirectorContract c;c.pid=p.id;c.months=std::max(0,11-std::max(0,mgr.lastMonth));c.priority=p.id==U.captainPid?100:directorProtected(p.id)?90:p.age<=23&&p.pot>=p.overall()+5?80:p.age>=33?20:50;textTo(c.reason,c.priority>=90?"Titulaire / capitaine à sécuriser":c.priority>=80?"Jeune à potentiel":c.priority<=20?"Joueur vieillissant, priorité faible":"Fin de contrat à examiner");D.contracts.push_back(c);}
 std::sort(D.contracts.begin(),D.contracts.end(),[](auto a,auto b){return a.priority>b.priority;});
 int young=0,old=0;for(auto& p:U.squad){young+=p.age<=23;old+=p.age>=32;}D.report.push_back(fmt("EFFECTIF : %d joueurs, %d jeunes, %d de 32 ans ou plus.",(int)U.squad.size(),young,old));for(auto& n:D.needs)if(n.priority)D.report.push_back(std::string("BESOIN ")+detailedPositionName(n.position)+" : "+n.reason);if(D.request.position>=0&&countAt(U,D.request.position)>=3)D.report.push_back("DÉSACCORD : ce poste compte déjà trois joueurs capables d'y évoluer ; votre demande reste prioritaire.");
 D.report.push_back(fmt("CONTRATS : %d dossiers à examiner.",(int)D.contracts.size()));D.report.push_back("FINANCES : budget "+money(mgr.budget)+" ; salaires joueurs + staff "+money(wageBill(userTeam)+staffWages(*this))+" / an.");D.report.push_back("ENVELOPPE DS : "+money(std::max<int64_t>(0,std::min(D.limits.boardFees,D.limits.budgetBase*D.limits.budgetPct/100)-D.limits.used))+" disponibles.");
 if(!research)return;D.targets.clear();int position=D.request.position>=0?D.request.position:!D.needs.empty()?D.needs[0].position:DP_BU;
 std::vector<std::pair<int,int>> clubs;for(int t=0;t<(int)g_world.teams.size();t++){const auto& T=g_world.teams[t];if(t==userTeam||T.kind!=TK_CLUB||T.youth==8||(T.youth==6)!=(U.youth==6)&&!T.freeAgents)continue;if(T.youth&&T.youth!=6&&T.parent!=userTeam)continue;bool local=T.nation==U.nation&&(T.district==U.district&&U.district>=0||T.region==U.region&&U.region>=0);if(U.status==CS_AMATEUR&&!T.freeAgents&&!local&&T.parent!=userTeam)continue;if(U.status!=CS_PRO&&T.nation!=U.nation&&!T.freeAgents)continue;if(T.nation!=U.nation&&!T.freeAgents&&D.profile.skill[DK_INTERNATIONAL]<55)continue;if(T.rating>U.rating+15&&!T.freeAgents&&T.parent!=userTeam)continue;int priority=T.parent==userTeam?-100:T.freeAgents?-90:local?-70:T.nation==U.nation?-30:0;clubs.push_back({priority,t});}
 std::stable_sort(clubs.begin(),clubs.end());int known=U.status==CS_AMATEUR?12+D.profile.skill[DK_NATIONAL]/5:30+D.profile.skill[DK_MARKET];int tested=0;
 for(auto item:clubs){if(tested++>=known)break;int t=item.second;g_world.ensureSquad(t);const auto& T=g_world.teams[t];if(sportingMode()&&sporting.scouting.nation>=0&&T.nation!=sporting.scouting.nation&&!T.freeAgents&&T.parent!=userTeam)continue;if(sportingMode()&&sporting.scouting.region>=0&&T.region!=sporting.scouting.region&&!T.freeAgents&&T.parent!=userTeam)continue;for(auto& p:T.squad){if(sportingMode()&&(p.age<sporting.scouting.minAge||p.age>sporting.scouting.maxAge||p.pot<sporting.scouting.minPotential))continue;if(!compatible(U,p)||p.age<D.limits.minAge||p.age>D.limits.maxAge||p.age<D.request.minAge||p.age>D.request.maxAge||p.overall()<D.request.minLevel||positionFamiliarity(p,position)<50)continue;if(U.status==CS_AMATEUR&&p.contract==0&&p.overall()>55&&T.parent!=userTeam)continue;if(U.status==CS_AMATEUR&&T.freeAgents&&p.nation!=U.nation)continue;if(p.overall()>teamReputation(userTeam)+14&&T.parent!=userTeam)continue;
  bool free=T.freeAgents||T.parent==userTeam;int fee=free?0:p.value();int wage=U.status==CS_AMATEUR?0:wageDemand(p,userTeam);bool loanCandidate=!free&&p.overall()<=T.rating-2&&wage*D.request.loanWagePct/100<=D.limits.maxWage;if(fee>D.limits.maxFee&&!loanCandidate||wage>D.limits.maxWage&&!loanCandidate)continue;bool borrowed=false;for(auto& l:loans)if(l.pid==p.id)borrowed=true;if(borrowed)continue;DirectorTarget c;c.pid=p.id;c.club=t;c.age=p.age;c.position=p.positions.primary;c.level=p.overall();c.potential=p.pot;c.fee=fee;c.wage=wage;c.freePlayer=free;c.loan=loanCandidate;if(loanCandidate&&fee>D.limits.maxFee){c.fee=0;c.wage=wage*D.request.loanWagePct/100;}c.knowledge=std::clamp(25+D.profile.skill[DK_MARKET]/2+(T.nation==U.nation?D.profile.skill[DK_NATIONAL]/4:D.profile.skill[DK_INTERNATIONAL]/4),20,99);personalityScout(p,t,D.profile.skill[DK_MARKET],c.knowledge);c.interest=std::clamp(70+(teamReputation(userTeam)-p.overall())*2,10,95);c.score=directorTargetScore(p,t,position);textTo(c.reason,(D.request.position>=0?"Demande de l'entraîneur : ":"Besoin de l'effectif : ")+std::string(detailedPositionName(position))+" ; "+directorPhilosophyName(D.profile.philosophy));D.targets.push_back(c);
 }}
 std::stable_sort(D.targets.begin(),D.targets.end(),[](auto a,auto b){return a.score>b.score;});if(D.targets.size()>18)D.targets.resize(18);D.lastResearch=season.now;D.report.push_back(fmt("RECHERCHE : %d cibles accessibles identifiées ; réseau limité à %d clubs.",(int)D.targets.size(),known));
}
static bool delegated(const DirectorState& D,const DirectorNegotiation& n){if(n.chosen)return D.mode[DD_OFFERS]>=DM_NEGOTIATE&&D.mode[DD_FEES]>=DM_NEGOTIATE&&D.mode[DD_CONTRACTS]>=DM_NEGOTIATE&&D.mode[DD_AGENTS]>=DM_NEGOTIATE;return D.mode[DD_OFFERS]==DM_AUTO&&D.mode[DD_FEES]==DM_AUTO&&D.mode[DD_CONTRACTS]==DM_AUTO&&D.mode[DD_AGENTS]==DM_AUTO;}
bool Career::directorStart(int pid,bool loan,std::string& msg){directorSync();if(!directorEnabled()||!director.profile.name[0]){msg="Directeur sportif indisponible.";return false;}int i,t=g_world.findPlayer(pid,&i);if(t<0||t==userTeam){msg="Cible introuvable ou déjà au club.";return false;}for(auto& n:director.negotiations)if(n.pid==pid&&n.phase!=DN_DONE&&n.phase!=DN_FAILED&&n.phase!=DN_CANCELLED){msg="Dossier déjà ouvert.";return false;}
 DirectorNegotiation n;n.pid=pid;n.from=t;n.chosen=1;n.kind=loan;n.wagePct=director.request.loanWagePct;n.started=n.next=season.now;const Player& p=g_world.teams[t].squad[i];int skill=(director.profile.skill[DK_NEGOTIATE]*2+director.profile.skill[DK_AGENTS]+director.profile.skill[DK_CONTRACT])/4;n.fee=g_world.teams[t].freeAgents||g_world.teams[t].parent==userTeam||loan?0:(int)std::ceil(p.value()*(1.12-skill*.002));n.wage=g_world.teams[userTeam].status==CS_AMATEUR?0:(int)std::ceil(wageDemand(p,userTeam)*(0.98+(100-skill)*.003));if(sportingMode())for(auto& a:sporting.agents)if(a.id==p.id%24)n.wage=(int)std::ceil(n.wage*(1.1-a.relation*.002));n.years=p.age>=31?2:p.age<=23?4:3;if(!delegated(director,n)){msg="Confiez au moins les offres, indemnités, contrats et contacts au DS (Négociation ou Complète).";return false;}if(loan&&director.mode[DD_LOAN_IN]<DM_NEGOTIATE){msg="Les prêts entrants sont encore manuels.";return false;}
 textTo(n.message,"Cible choisie par l'entraîneur ; négociation programmée.");director.negotiations.push_back(n);msg=n.message;note(*this,msg);return true;
}
static void finishNote(Career& K,DirectorNegotiation& n,int phase,const std::string& msg){n.phase=phase;textTo(n.message,msg);note(K,msg);}
static bool execute(Career& K,DirectorNegotiation& n,std::string& msg){int idx,t=g_world.findPlayer(n.pid,&idx);if(t<0||t==K.userTeam){msg="Cible indisponible.";return false;}if(t!=n.from){msg="La cible a changé de club : ouvrez un nouveau dossier.";n.phase=DN_FAILED;return false;}const auto p=g_world.teams[t].squad[idx];if(p.age<K.director.limits.minAge||p.age>K.director.limits.maxAge){msg="La cible ne respecte plus les limites d'âge.";n.phase=DN_FAILED;return false;}if(n.fee>K.director.limits.maxFee||(n.kind?playerWage(p)*n.wagePct/100:n.wage)>K.director.limits.maxWage){msg="Limite individuelle dépassée.";n.phase=DN_FAILED;return false;}
 int fee=n.fee+(n.kind?0:g_world.teams[K.userTeam].status==CS_AMATEUR?0:n.wage*n.years/10);if(!K.directorCanSpend(fee,n.kind?playerWage(p)*n.wagePct/100:n.wage,msg)){n.phase=DN_FAILED;return false;}int64_t before=K.mgr.budget;bool ok=false;
 if(n.kind){ok=K.loanIn(n.pid,msg,n.wagePct);if(ok){DirectorLoanTerms l;l.pid=n.pid;l.from=t;l.to=K.userTeam;l.year=K.year;l.wagePct=n.wagePct;l.option=std::min(p.value(),K.director.limits.maxFee);K.director.loanTerms.push_back(l);}}
 else {int result=K.signPlayer(n.pid,n.fee,n.wage,n.years,msg);ok=result==1;if(result==0)n.fee=std::max(n.fee+1,(int)std::ceil(n.fee*1.1));else if(result==-1)n.wage=std::max(n.wage+1,(int)std::ceil(n.wage*1.1));else if(result==-2)n.phase=DN_FAILED;}
 if(ok){K.director.limits.used+=std::max<int64_t>(0,before-K.mgr.budget);n.phase=DN_DONE;}return ok;
}
bool Career::directorApprove(int index,std::string& msg){if(index<0||index>=(int)director.negotiations.size()){msg="Dossier invalide.";return false;}auto& n=director.negotiations[index];if(n.phase!=DN_APPROVAL){msg="Le dossier n'est pas prêt pour validation.";return false;}n.approved=1;bool ok=execute(*this,n,msg);textTo(n.message,msg);if(!ok&&n.phase!=DN_FAILED){n.approved=0;n.phase=DN_PLAYER;n.next=season.now+.2;}note(*this,msg);return ok;}
bool Career::directorRenew(int pid,std::string& msg){for(auto& l:loans)if(l.pid==pid&&l.to==userTeam){msg="Le contrat du joueur prêté appartient au club prêteur.";return false;}int i;if(g_world.findPlayer(pid,&i)!=userTeam){msg="Joueur absent du club.";return false;}const auto& p=g_world.teams[userTeam].squad[i];int wage=p.contract==2?0:std::max(wageDemand(p,userTeam),playerWage(p));if(!directorCanSpend(wage/10,wage,msg,playerWage(p)))return false;int64_t before=mgr.budget;bool ok=extendContract(pid,msg);if(ok)director.limits.used+=before-mgr.budget;return ok;}
int Career::directorLoanClub(int pid)const{int idx;if(g_world.findPlayer(pid,&idx)!=userTeam)return -1;const auto& P=g_world.teams[userTeam].squad[idx];const auto& U=g_world.teams[userTeam];int lv=teamLevel(userTeam);std::vector<std::pair<int,int>> choices;
 for(int t=0;t<(int)g_world.teams.size();t++){const auto& T=g_world.teams[t];if(t==userTeam||T.kind!=TK_CLUB||T.parent>=0||T.freeAgents||T.youth&&T.youth!=6||T.nation!=U.nation||(T.youth==6)!=(P.gender==1)||T.rating>P.overall()+8||T.rating<P.overall()-16||loansIn(t)>=loanLimitIn(t))continue;int l2=teamLevel(t);if(l2<lv||l2>lv+2||l2>=99)continue;if(U.status==CS_AMATEUR&&T.region!=U.region)continue;int partnerBonus=0;if(sportingMode())for(auto& partner:sporting.partners)if(partner.club==t)partnerBonus=-30;choices.push_back({partnerBonus+(T.region==U.region?-20:0)+(int)std::abs(T.rating-P.overall()),t});}
 std::sort(choices.begin(),choices.end());int examined=0;for(auto c:choices){if(examined++>10+director.profile.skill[DK_LOAN]/2)break;g_world.ensureSquad(c.second);const auto& T=g_world.teams[c.second];int stronger=0;for(auto& p:T.squad)if(p.pos==P.pos&&p.overall()>=P.overall())stronger++;if(stronger<2)return c.second;}return -1;
}
bool Career::directorExercise(int pid,std::string& msg){auto it=std::find_if(director.loanTerms.begin(),director.loanTerms.end(),[&](auto l){return l.pid==pid&&l.to==userTeam;});if(it==director.loanTerms.end()||it->option<=0){msg="Pas d'option d'achat négociée.";return false;}int idx;if(g_world.findPlayer(pid,&idx)!=userTeam){msg="Joueur absent.";return false;}int wage=playerWage(g_world.teams[userTeam].squad[idx]);if(it->option>director.limits.maxFee||!directorCanSpend(it->option,wage,msg,wage*it->wagePct/100))return false;int64_t before=mgr.budget;bool ok=buyLoanOption(pid,it->option,msg);if(ok){director.limits.used+=before-mgr.budget;director.loanTerms.erase(it);}return ok;}
void Career::directorTick(){directorSync();if(!directorEnabled()||!director.profile.name[0])return;auto& D=director;if(season.now<D.lastTick+.05)return;D.lastTick=season.now;
 bool any=false;for(auto mode:D.mode)if(mode)any=true;bool pending=false;for(auto& n:D.negotiations)if(n.phase<=DN_APPROVAL||n.phase==DN_PAUSED)pending=true;if(!any&&!pending)return;
 if(D.lastResearch<season.now-.8){directorAnalyse(D.mode[DD_SEARCH]>DM_MANUAL&&D.mode[DD_SHORTLIST]>DM_MANUAL);if(!D.targets.empty()&&(D.mode[DD_SEARCH]==DM_ADVICE||D.mode[DD_SHORTLIST]==DM_ADVICE))note(*this,fmt("%d recrues proposées ; aucune décision prise en mode Conseil.",(int)D.targets.size()));}
 if(transferWindow()&&D.mode[DD_OFFERS]==DM_AUTO){int live=0;for(auto& n:D.negotiations)if(n.phase<=DN_APPROVAL||n.phase==DN_PAUSED)live++;if(live<2)for(auto& c:D.targets){bool known=false;for(auto& n:D.negotiations)if(n.pid==c.pid)known=true;if(known||c.fee==0&&!c.freePlayer)continue;int idx,t=g_world.findPlayer(c.pid,&idx);if(t<0)continue;if(g_world.teams[t].squad[idx].age<=20&&D.mode[DD_YOUTH]!=DM_AUTO)continue;std::string msg;if(directorStart(c.pid,false,msg)){D.negotiations.back().chosen=0;break;}}}
 if(transferWindow()&&D.mode[DD_LOAN_IN]==DM_AUTO){int live=0;for(auto& n:D.negotiations)if(n.kind&&n.phase<=DN_APPROVAL)live++;if(!live)for(auto& c:D.targets)if(!c.freePlayer&&c.loan){std::string msg;if(directorStart(c.pid,true,msg)){D.negotiations.back().chosen=0;break;}}}
 Rng rng(D.rng);
 for(auto& n:D.negotiations){if(n.phase==DN_DONE||n.phase==DN_FAILED||n.phase==DN_CANCELLED||n.phase==DN_APPROVAL)continue;
  if(!delegated(D,n)||n.kind&&D.mode[DD_LOAN_IN]<DM_NEGOTIATE){if(n.phase!=DN_PAUSED){n.phase=DN_PAUSED;textTo(n.message,"Responsabilité reprise par l'entraîneur : aucune signature automatique.");}continue;}if(n.phase==DN_PAUSED){n.phase=DN_QUEUED;n.next=season.now;}
  for(int steps=0;steps<6&&season.now>=n.next&&n.phase<DN_APPROVAL;steps++){if(!transferWindow()&&!jokerAvailable()){finishNote(*this,n,DN_FAILED,"Mercato fermé : dossier abandonné.");break;}double delay=.12+(100-D.profile.skill[DK_NEGOTIATE])*.005;n.next+=delay;
   if(n.phase==DN_QUEUED){n.phase=DN_CLUB;textTo(n.message,"Première offre préparée dans les limites du club.");}
   else if(n.phase==DN_CLUB){n.phase=DN_PLAYER;textTo(n.message,"Discussion du salaire, durée et prime de signature.");}
   else {n.attempts++;if(n.attempts>5){finishNote(*this,n,DN_FAILED,"Négociation sans accord : le DS abandonne.");break;}if(rng.range(0,999)<(100-D.profile.skill[DK_NEGOTIATE])*2){finishNote(*this,n,DN_FAILED,"Discussions interrompues : aucun engagement financier.");break;}
    auto automatic=n;automatic.chosen=0;bool full=delegated(D,automatic);
    if(n.chosen&&!full&&!n.approved){n.phase=DN_APPROVAL;textTo(n.message,"Proposition négociée : validation humaine nécessaire avant signature.");note(*this,n.message);break;}
    std::string msg;if(execute(*this,n,msg)){note(*this,msg);break;}textTo(n.message,msg);if(n.phase==DN_FAILED){note(*this,msg);break;}
   }
  }
 }
 D.rng=rng.s;
 // Contract advice is non-binding; complete delegation calls the existing renewal transaction.
 auto contracts=D.contracts;for(auto& c:contracts)if(c.priority>=70){int idx;if(g_world.findPlayer(c.pid,&idx)!=userTeam)continue;if(contractYears(g_world.teams[userTeam].squad[idx])>1)continue;auto name=g_world.teams[userTeam].squad[idx].name;if(D.mode[DD_RENEWALS]==DM_AUTO){std::string msg;if(directorRenew(c.pid,msg))note(*this,msg);}else if(D.mode[DD_RENEWALS]==DM_ADVICE&&D.announcedYear!=year)note(*this,"Prolongation conseillée : "+name+" — "+c.reason);}
 if(D.mode[DD_RENEWALS]==DM_ADVICE)D.announcedYear=year;
 if(transferWindow()){
  if(D.mode[DD_LIST]==DM_AUTO)for(auto& p:g_world.teams[userTeam].squad)if(!directorProtected(p.id)&&p.age>=31&&p.apps<2&&p.pot<=p.overall())directorPolicy(p.id,DS_FOR_SALE,false);
  if(D.mode[DD_SALES]==DM_AUTO)for(int k=(int)mgr.offers.size()-1;k>=0;k--){auto o=mgr.offers[k];if(directorProtected(o.pid))continue;int idx;if(g_world.findPlayer(o.pid,&idx)!=userTeam)continue;const auto& p=g_world.teams[userTeam].squad[idx];bool allowed=false;for(auto& policy:D.policies)if(policy.pid==p.id&&(policy.status==DS_FOR_SALE||policy.status==DS_AVAILABLE))allowed=true;if(!allowed)continue;int minimum=(int)(p.value()*(.8+D.profile.skill[DK_SELL]*.002));std::string msg;if(o.fee>=minimum){if(answerOffer(k,0,msg))note(*this,msg);}else if(D.profile.skill[DK_SELL]>=50)answerOffer(k,2,msg);}
  if(D.mode[DD_LOAN_OUT]==DM_AUTO&&D.mode[DD_LOAN_CLUB]==DM_AUTO){std::vector<int> ids;for(auto& p:g_world.teams[userTeam].squad)if(p.age<=23&&!directorProtected(p.id)&&p.apps<3)ids.push_back(p.id);for(int pid:ids){int t=directorLoanClub(pid);if(t<0)continue;std::string msg;if(loanOut(pid,msg,t,50)){note(*this,msg);break;}}}
 }
 if(D.mode[DD_STAFF]==DM_AUTO){std::set<int> roles;for(auto& s:mgr.staff)roles.insert(s.role);for(int role:{SR_SCOUT,SR_YOUTH,SR_MEDIC})if(!roles.count(role)){int level=std::clamp((int)D.profile.skill[DK_STAFF]/20,1,g_world.teams[userTeam].status==CS_AMATEUR?2:5);StaffMember s=makeStaff(role,level,g_world.teams[userTeam].status,rng);std::string msg;if(directorCanSpend(0,s.wage,msg)){mgr.staff.push_back(s);note(*this,std::string("Staff recruté : ")+s.name+" — "+staffRoleName(role));}break;}}
 D.rng=rng.s;
}
template<class T>static void vectorIO(Writer& w,std::vector<T>& v){w.vpod(v);}template<class T>static void vectorIO(Reader& r,std::vector<T>& v){if(r.packed){r.vpod(v);return;}unsigned n=0;r.pod(n);if(!r.ok||n>3000){r.ok=false;return;}long pos=ftell(r.f);fseek(r.f,0,SEEK_END);long end=ftell(r.f);fseek(r.f,pos,SEEK_SET);if(pos<0||end<pos||(uint64_t)n*sizeof(T)>(uint64_t)(end-pos)){r.ok=false;return;}v.resize(n);if(n&&fread(v.data(),sizeof(T),n,r.f)!=n)r.ok=false;}
template<class IO>static void dataIO(IO& io,DirectorState& D){io.pod(D.club);io.pod(D.policyYear);io.pod(D.staffYear);io.pod(D.announcedYear);io.pod(D.lastResearch);io.pod(D.lastTick);io.pod(D.rng);io.pod(D.profile);io.pod(D.limits);io.pod(D.request);io.pod(D.mode);vectorIO(io,D.needs);vectorIO(io,D.targets);vectorIO(io,D.negotiations);vectorIO(io,D.policies);vectorIO(io,D.contracts);vectorIO(io,D.loanTerms);vectorIO(io,D.staffContracts);}
void directorSave(Writer& w,const Career& K){auto& D=const_cast<DirectorState&>(K.director);dataIO(w,D);}
void directorLoad(Reader& r,Career& K){K.director=DirectorState();auto& D=K.director;dataIO(r,D);D.profile.name[31]=0;for(auto& c:D.staffContracts)c.name[31]=0;for(auto& n:D.negotiations)n.message[179]=0;for(auto& n:D.needs)n.reason[127]=0;for(auto& n:D.targets)n.reason[159]=0;for(auto& c:D.contracts)c.reason[119]=0;if(D.club < -1||D.club>=(int)g_world.teams.size()||D.club>=0&&D.club!=K.userTeam||D.profile.philosophy>=DPH_COUNT||D.limits.minAge<13||D.limits.maxAge>50||D.limits.minAge>D.limits.maxAge||D.limits.budgetPct<0||D.limits.budgetPct>100||D.request.position < -1||D.request.position>=DP_COUNT||D.request.loanWagePct<0||D.request.loanWagePct>100||D.request.profile < -1||D.request.profile>=DPH_COUNT||!std::isfinite(D.lastTick)||!std::isfinite(D.lastResearch))r.ok=false;for(auto mode:D.mode)if(mode>DM_AUTO)r.ok=false;for(auto skill:D.profile.skill)if(skill>100)r.ok=false;for(auto& n:D.negotiations)if(n.phase<0||n.phase>DN_CANCELLED||n.kind<0||n.kind>1||n.fee<0||n.wage<0||n.wagePct<0||n.wagePct>100||n.years<1||n.years>5||!std::isfinite(n.next)||!std::isfinite(n.started))r.ok=false;for(auto& p:D.policies)if(p.status<0||p.status>DS_FOR_LOAN||p.noSell>1)r.ok=false;}
