#include "game.h"
#include "serial.h"
#include <cstring>
#include <set>
namespace {
int limit(int n){return std::clamp(n,0,100);}
bool clubOk(int t){return t>=0&&t<(int)g_world.teams.size()&&g_world.teams[t].kind==TK_CLUB&&!g_world.teams[t].freeAgents;}
int family(int t){return clubOk(t)&&g_world.teams[t].parent>=0?g_world.teams[t].parent:t;}
const PlayerClubRelation* relation(const Career& K,int pid,int club){auto it=K.personalities.players.find(pid);if(it==K.personalities.players.end())return nullptr;for(auto& R:it->second.relations)if(R.clubId==family(club))return &R;return nullptr;}
bool once(std::vector<uint64_t>& list,uint64_t k){auto at=std::lower_bound(list.begin(),list.end(),k);if(at!=list.end()&&*at==k)return false;list.insert(at,k);return true;}
int monthKey(const Career& K){return K.year*12+std::clamp((int)(K.season.now/4.2),0,11);}
}
int personalityTrait(const PlayerPersonality& P,int i){switch(i){case 0:return P.ambition;case 1:return P.professionalism;case 2:return P.loyalty;case 3:return P.aggression;case 4:return P.leadership;case 5:return P.composure;case 6:return P.consistency;case 7:return P.bigMatchTemperament;case 8:return P.sensitivity;default:return P.foreignAdaptability;}}
void personalitySetTrait(PlayerPersonality& P,int i,int n){n=limit(n);switch(i){case 0:P.ambition=n;break;case 1:P.professionalism=n;break;case 2:P.loyalty=n;break;case 3:P.aggression=n;break;case 4:P.leadership=n;break;case 5:P.composure=n;break;case 6:P.consistency=n;break;case 7:P.bigMatchTemperament=n;break;case 8:P.sensitivity=n;break;case 9:P.foreignAdaptability=n;break;}}
const char* personalityTraitName(int i){static const char* n[]={"Ambition","Professionnalisme","Loyauté","Agressivité","Leadership","Sang-froid psychologique","Régularité","Grands matchs","Susceptibilité","Adaptation étrangère"};return n[std::clamp(i,0,9)];}
const char* personalityGrade(int n){return n<15?"Très faible":n<30?"Faible":n<50?"Moyen":n<65?"Bon":n<80?"Élevé":n<95?"Très élevé":"Exceptionnel";}
PlayerPersonality generatePersonality(const Player& p){Rng r((uint64_t)(unsigned)p.id*0xD6E8FEB86659FD93ULL^0x17294FA2ULL);PlayerPersonality P;for(int i=0;i<10;i++)personalitySetTrait(P,i,r.range(10,94));P.leadership=limit(P.leadership-12+std::clamp((int)p.age-17,0,20));return P;}
PlayerPersonality personalityTraits(const Career& K,const Player& p){auto it=K.personalities.players.find(p.id);return it==K.personalities.players.end()?generatePersonality(p):it->second.traits;}
std::string personalitySummary(const PlayerPersonality& P,int age){if(P.leadership>=80&&P.loyalty>=75)return "Leader loyal";if(P.leadership>=85&&P.professionalism>=70)return "Capitaine naturel";if(P.professionalism>=80&&age<=21)return "Jeune très professionnel";if(P.professionalism>=75&&P.ambition>=75)return "Professionnel ambitieux";if(P.aggression>=75&&P.sensitivity>=70)return "Compétiteur caractériel";if(P.ambition>=75&&P.consistency<45)return "Ambitieux instable";if(P.consistency<40)return "Talent irrégulier";if(P.loyalty>=80)return "Fidèle au club";return P.professionalism>=65?"Professionnel discret":"Personnalité nuancée";}
bool Career::personalityEnabled()const{return kind==CK_CLUB&&!opts.lite&&!euroOnly;}
PlayerClubRelation& Career::personalityRelation(PersonalityPlayer& P,int club){club=family(club);for(auto& R:P.relations)if(R.clubId==club)return R;PlayerClubRelation R;R.clubId=club;R.joinedYear=year;R.lastTier=teamLevel(club);P.relations.push_back(R);if(P.relations.size()>80)P.relations.erase(P.relations.begin());return P.relations.back();}
PersonalityPlayer& Career::personalityPlayer(const Player& p,int club){auto it=personalities.players.find(p.id);if(it==personalities.players.end()){PersonalityPlayer P;P.pid=p.id;P.traits=generatePersonality(p);P.lastYear=year;P.lastAge=p.age;snprintf(P.name,sizeof P.name,"%s",p.name.c_str());it=personalities.players.emplace(p.id,P).first;}auto& P=it->second;if(family(club)==userTeam){P.knowledge=P.scoutQuality=100;}if(!P.retired&&P.activeClub!=club){P.activeClub=club;if(clubOk(club)){auto& R=personalityRelation(P,club);if(R.seasons==0&&R.lastMonth<0){R.formedHere=g_world.teams[club].parent>=0||p.age<=18&&p.hist.empty();R.attachment=R.formedHere?45:20;R.fanPopularity=R.formedHere?35:20;R.managerRelationship=60;R.squadInfluence=limit(P.traits.leadership/2+p.age/3);bool foreign=p.nation>=0&&p.nation!=g_world.teams[club].nation;R.adaptationProgress=foreign?std::min(70,10+P.traits.foreignAdaptability/3+(p.age>=27?15:0)):100;for(auto& h:p.hist)if(h.team>=0&&h.team<(int)g_world.teams.size()&&g_world.teams[h.team].nation==g_world.teams[club].nation)R.adaptationProgress=100;for(auto& l:loans)if(l.pid==p.id&&l.to==club)R.temporary=1;}}}return P;}
void Career::personalityInitClub(int club){if(!personalityEnabled()||!clubOk(club))return;auto& T=g_world.teams[club];for(auto& p:T.squad)if(p.id>0)personalityPlayer(p,club);if(std::none_of(T.squad.begin(),T.squad.end(),[&](const Player& p){return p.id==T.captainPid;})&&!T.squad.empty()){auto best=std::max_element(T.squad.begin(),T.squad.end(),[&](const Player& a,const Player& b){return personalityCaptainScore(*this,a,club)<personalityCaptainScore(*this,b,club);});personalityCaptain(club,best->id);}}
void Career::personalityEvent(PersonalityPlayer& P,int club,int type,const std::string& msg){for(auto& e:P.events)if(e.year==year&&e.club==family(club)&&e.type==type)return;PersonalityEvent e;e.year=year;e.club=family(club);e.type=type;snprintf(e.text,sizeof e.text,"%s",msg.c_str());P.events.push_back(e);if(P.events.size()>60)P.events.erase(P.events.begin());if(family(club)==userTeam&&(!sportingMode()||sporting.employed))season.news.push_back("[Personnalité] "+msg);if((type==2||type==4||type==5||type==6)&&clubOk(family(club))&&(family(club)==userTeam||clubHistories.count(family(club)))){museumState(family(club));MuseumEvent m;m.year=year;m.time=season.now;m.category=MH_PLAYER;snprintf(m.text,sizeof m.text,"%s",msg.c_str());clubHistories[family(club)].timeline.push_back(m);}}
float personalityTrainingMultiplier(const Career& K,const Player& p){if(!K.personalityEnabled())return 1;auto P=personalityTraits(K,p);return std::clamp(.55f+P.professionalism*.007f+P.ambition*.002f,.6f,1.45f);}
float personalityLearningMultiplier(const Career& K,const Player& p){if(!K.personalityEnabled())return 1;auto P=personalityTraits(K,p);return .6f+P.professionalism*.008f;}
int personalityAnnualGain(const Career& K,const Player& p,int gain){if(!K.personalityEnabled())return gain;auto P=personalityTraits(K,p);float adjusted=gain>=0?gain*personalityTrainingMultiplier(K,p):gain*(1.2f-P.professionalism*.0045f);Rng r((uint64_t)(unsigned)p.id^((uint64_t)K.year<<32)^0x6A731AULL);int value=(int)std::floor(adjusted);if(r.f()<adjusted-value)value++;return gain>0?std::clamp(value,0,std::max(0,(int)p.pot-p.overall())):value;}
int personalitySalary(const Career& K,const Player& p,int club,int base){if(!K.personalityEnabled()||!clubOk(club))return base;auto P=personalityTraits(K,p);auto R=relation(K,p.id,club);float factor=1+(P.ambition-50)*.0015f-(P.loyalty-50)*.001f-(R?R->attachment*.0006f:0);return std::max(1,(int)std::ceil(base*std::clamp(factor,.8f,1.2f)));}
bool Career::personalityContract(const Player& p,int club,int years,std::string& msg)const{if(!personalityEnabled())return true;auto P=personalityTraits(*this,p);auto R=relation(*this,p.id,club);if(R&&R->transferRequested&&P.ambition>75&&P.loyalty<45&&R->attachment<60){msg=p.name+" souhaite un projet plus ambitieux avant de prolonger.";return false;}if(years>=4&&p.age>=28&&P.loyalty<45&&(!R||R->attachment<60)){msg=p.name+" préfère un engagement plus court.";return false;}return true;}
int personalityCaptainScore(const Career& K,const Player& p,int club){auto P=personalityTraits(K,p);auto R=relation(K,p.id,club);return P.leadership*4+P.professionalism+P.loyalty+(R?R->attachment+R->seasons*8:0)+std::min(35,(int)p.age)+(p.id==g_world.teams[club].captainPid?20:0);}
bool Career::personalityMentor(int club,int pid,int mentor,std::string& msg){if(!personalityEnabled()||club!=userTeam){msg="Mentorat réservé au club dirigé.";return false;}auto& T=g_world.teams[club];auto young=std::find_if(T.squad.begin(),T.squad.end(),[&](auto& p){return p.id==pid;});auto elder=std::find_if(T.squad.begin(),T.squad.end(),[&](auto& p){return p.id==mentor;});if(young==T.squad.end()||young->age>23||pid==mentor||mentor&& (elder==T.squad.end()||elder->age<25)){msg="Choisir un jeune de 23 ans maximum et un mentor de 25 ans minimum dans le même effectif.";return false;}auto& P=personalityPlayer(*young,club);auto& R=personalityRelation(P,club);if(mentor){auto traits=personalityTraits(*this,*elder);if(traits.professionalism<60||traits.leadership<60){msg="Le mentor doit être professionnel et capable de guider le groupe.";return false;}}R.mentorPid=mentor;msg=young->name+(mentor?" est accompagné par "+elder->name:" poursuit sa progression sans mentor désigné.");personalityEvent(P,club,2,msg);return true;}
void Career::personalityCaptain(int club,int pid){if(!personalityEnabled()||!clubOk(club))return;auto& T=g_world.teams[club];if(std::none_of(T.squad.begin(),T.squad.end(),[&](const Player& p){return p.id==pid;}))return;int old=T.captainPid;if(old==pid)return;for(auto& p:T.squad){if(p.id==old){personalityDecision(p,club,3);auto& R=personalityRelation(personalityPlayer(p,club),club);R.captaincy=0;}if(p.id==pid){auto& P=personalityPlayer(p,club);auto& R=personalityRelation(P,club);R.captaincy=1;R.attachment=limit(R.attachment+3);R.fanPopularity=limit(R.fanPopularity+3);p.morale=(uint8_t)limit(p.morale+std::max(1,P.traits.leadership/25));personalityEvent(P,club,4,p.name+" porte le brassard et prend ses responsabilités.");}}T.captainPid=pid;if(T.vicePid==pid)T.vicePid=0;}
void Career::personalityDecision(Player& p,int club,int type){if(!personalityEnabled())return;auto& P=personalityPlayer(p,club);auto& R=personalityRelation(P,club);int impact=std::max(0,(P.traits.sensitivity-40)/20);if(type==0)impact=std::max(0,(P.traits.sensitivity+P.traits.ambition-P.traits.loyalty-70)/25);if(type==1&&P.traits.professionalism>=75)impact=std::max(0,impact-1);if(impact==0||R.lastDecision>=monthKey(*this))return;R.lastDecision=monthKey(*this);p.morale=(uint8_t)std::clamp((int)p.morale-impact,10,100);R.managerRelationship=limit(R.managerRelationship-impact);if(impact>=2)personalityEvent(P,club,8,p.name+(type==0?" accepte mal sa période sur le banc.":type==1?" est déçu de son remplacement.":type==3?" a mal vécu la perte du brassard.":" est déçu de cette décision contractuelle / critique."));}
void Career::personalityMonth(int club){if(!personalityEnabled()||!clubOk(club))return;personalityInitClub(club);auto& T=g_world.teams[club];int key=monthKey(*this);std::map<int,const Player*> squad;for(auto& p:T.squad)squad[p.id]=&p;for(auto& p:T.squad){auto& P=personalityPlayer(p,club);auto& R=personalityRelation(P,club);if(R.lastMonth>=key)continue;R.lastMonth=key;auto& Q=P.traits;uint32_t coach=club==userTeam?hashStr(managerName):0;if(coach&&R.coachHash&&R.coachHash!=coach)R.managerRelationship=limit(50+Q.professionalism/5-Q.sensitivity/10);R.coachHash=coach;int compatriots=0;for(auto& mate:T.squad)compatriots+=mate.id!=p.id&&mate.nation==p.nation;int apps=std::max(0,(int)p.apps-R.lastApps);if(R.adaptationProgress<100){int gain=3+Q.foreignAdaptability/20+std::min(3,compatriots)+std::min(2,apps)+(p.age>=25?1:0)+(p.morale>65?1:0)+(R.mentorPid?1:0);R.adaptationProgress=limit(R.adaptationProgress+gain);p.morale=(uint8_t)limit(p.morale+(Q.foreignAdaptability>=60?1:-1));if(R.adaptationProgress==100)personalityEvent(P,club,5,p.name+" est maintenant pleinement adapté à son nouvel environnement.");}else if(Q.loyalty>=75&&p.morale<60)p.morale=(uint8_t)limit(p.morale+1);if(R.mentorPid){auto it=squad.find(R.mentorPid);if(it==squad.end()||p.age>23)R.mentorPid=0;else if(key%3==0){auto M=personalityTraits(*this,*it->second);if(M.professionalism>Q.professionalism+10)Q.professionalism=limit(Q.professionalism+1);if(M.leadership>Q.leadership+15)Q.leadership=limit(Q.leadership+1);}}
 R.attachment=limit(R.attachment+(apps>0||Q.loyalty>=70?1:0));R.squadInfluence=limit((Q.leadership+R.attachment)/2+(R.captaincy?10:0));int goals=std::max(0,(int)p.goals-R.lastGoals);R.fanPopularity=limit(R.fanPopularity+std::min(3,goals)+(R.captaincy&&apps?1:0)+(Q.loyalty>=80&&apps?1:0));if(p.injured<=0)p.cond=(uint8_t)limit(p.cond+Q.professionalism/40);if(apps==0&&p.injured<=0&&Q.ambition>75){R.benchStreak++;if(R.benchStreak>=2)personalityDecision(p,club,0);}else R.benchStreak=0;if(Q.ambition>=80&&Q.loyalty<50&&R.stagnantSeasons>=2&&R.attachment<65&&!R.transferRequested){R.transferRequested=1;personalityEvent(P,club,1,p.name+" souhaite évoluer à un niveau supérieur après la stagnation du club.");}R.lastApps=p.apps;R.lastGoals=p.goals;}}
void Career::personalityMatchEnd(int ci,int mi){if(!personalityEnabled()||ci<0||ci>=(int)season.comps.size()||mi<0||mi>=(int)season.comps[ci].matches.size())return;auto& C=season.comps[ci];auto& M=C.matches[mi];if(!M.played)return;if(personalities.matchYear!=year){personalities.matches.clear();personalities.matchYear=year;}if(!once(personalities.matches,(uint64_t)(unsigned)ci<<32|(unsigned)mi))return;for(int side=0;side<2;side++){int club=side?M.away:M.home;if(!clubOk(club))continue;personalityMonth(club);auto& T=g_world.teams[club];int leaders=0;for(auto& p:T.squad){auto Q=personalityTraits(*this,p);if(Q.leadership>=80&&Q.loyalty>=65)leaders++;}bool lost=side?M.ag<M.hg:M.hg<M.ag;for(auto& p:T.squad){auto& P=personalityPlayer(p,club);auto& R=personalityRelation(P,club);int change=lost?-std::max(0,2-P.traits.loyalty/50-(leaders?1:0)):1;if(P.traits.sensitivity>=85&&lost&&R.managerRelationship<35)change--;p.morale=(uint8_t)std::clamp((int)p.morale+change,10,100);if(R.captaincy)R.squadInfluence=limit(R.squadInfluence+(lost?0:1));if(lost&&P.traits.professionalism<40&&P.traits.sensitivity>=85&&R.benchStreak>=3)personalityEvent(P,club,9,p.name+" traverse une tension avec le vestiaire ; le staff doit renouer le dialogue.");}}}
void Career::personalitySeasonEnd(){if(!personalityEnabled())return;for(int club=0;club<(int)g_world.teams.size();club++){auto& T=g_world.teams[club];if(!clubOk(club)||!T.squadGen)continue;personalityInitClub(club);for(auto& p:T.squad){auto& P=personalityPlayer(p,club);if(P.lastYear>=year+1)continue;P.lastYear=year+1;P.lastAge=p.age;auto& R=personalityRelation(P,club);R.seasons++;int tier=T.lastTier>=0?T.lastTier:teamLevel(club);bool promoted=R.lastTier>=0&&tier<R.lastTier;R.stagnantSeasons=promoted?0:R.stagnantSeasons+1;if(promoted){R.transferRequested=0;R.attachment=limit(R.attachment+4);}if(R.lastTier>=0&&tier>R.lastTier&&P.traits.loyalty>=75){R.attachment=limit(R.attachment+2);p.morale=(uint8_t)limit(p.morale+2);}R.lastTier=tier;bool title=false;for(auto& C:season.comps)if(C.done&&C.winner==club&&C.kind!=12){title=true;break;}if(title){R.stagnantSeasons=0;R.transferRequested=0;}R.attachment=limit(R.attachment+2+(title?4:0)+(R.captaincy?2:0));R.fanPopularity=limit(R.fanPopularity+(title?3:0)+(P.traits.loyalty>=75?1:0));if(p.age>=24&&p.age<=33)P.traits.leadership=limit(P.traits.leadership+1+(R.captaincy?1:0));if(p.age>=22&&P.traits.professionalism<85)P.traits.professionalism=limit(P.traits.professionalism+1);if(p.age>=25&&P.traits.sensitivity>20)P.traits.sensitivity--;if(R.attachment>=80)personalityEvent(P,club,6,p.name+" s'est profondément attaché au club.");if(P.traits.leadership>=80&&P.traits.leadership<=82)personalityEvent(P,club,7,p.name+" est devenu une voix importante du vestiaire.");R.lastApps=R.lastGoals=0;}}}
void Career::personalityTransfer(const Player& p,int from,int to){if(!personalityEnabled())return;auto& P=personalityPlayer(p,from);P.activeClub=to;if(!clubOk(to))return;bool known=false;for(auto& old:P.relations)known|=old.clubId==family(to);auto& R=personalityRelation(P,to);R.managerRelationship=60;R.transferRequested=R.benchStreak=0;R.mentorPid=0;R.lastApps=p.apps;R.lastGoals=p.goals;R.lastMonth=-1;R.temporary=0;for(auto& l:loans)if(l.pid==p.id&&l.to==to)R.temporary=1;if(family(from)!=family(to)&&!known){R.attachment=20;R.fanPopularity=20;R.adaptationProgress=p.nation>=0&&p.nation!=g_world.teams[to].nation?std::min(70,10+P.traits.foreignAdaptability/3):100;}if(family(from)==family(to))R.formedHere=1;}
void Career::personalityRetire(const Player& p,int club){if(!personalityEnabled())return;auto& P=personalityPlayer(p,club);P.retired=1;P.lastAge=p.age;personalityEvent(P,club,10,p.name+" prend sa retraite ; sa personnalité et ses liens au club restent dans les archives.");}
void Career::personalityScout(const Player& p,int club,int quality,int knowledge){if(!personalityEnabled())return;auto& P=personalityPlayer(p,club);P.knowledge=std::max(P.knowledge,limit(knowledge));P.scoutQuality=std::max(P.scoutQuality,limit(quality));}
std::string personalityScoutReport(const Career& K,const Player& p,int club){if(!K.personalityEnabled())return "";auto it=K.personalities.players.find(p.id);bool own=family(club)==K.userTeam;int knowledge=own?100:it==K.personalities.players.end()?0:it->second.knowledge;int quality=own?100:it==K.personalities.players.end()?0:it->second.scoutQuality;if(knowledge<30)return "Personnalité difficile à évaluer. Observation supplémentaire nécessaire.";auto P=personalityTraits(K,p);int count=knowledge<60?2:knowledge<85?5:10;std::string text=knowledge>=85?personalitySummary(P,p.age)+"\n":"Évaluation provisoire :\n";for(int i=0;i<count;i++){Rng r((uint64_t)(unsigned)p.id*1337+i*53);int noise=own?0:r.range(-1,1)*(100-quality)/12;int value=limit(personalityTrait(P,i)+noise);text+=std::string(personalityTraitName(i))+" : "+personalityGrade(value)+"\n";}if(!own)text+="Confiance de l'observation : "+std::string(personalityGrade(knowledge))+" ; estimation, pas une certitude.\n";return text;}
int personalityRecruitScore(const Career& K,const Player& p,int style){if(!K.personalityEnabled())return 0;auto it=K.personalities.players.find(p.id);if(it==K.personalities.players.end()||it->second.knowledge<30)return 0;auto& R=it->second;auto estimated=[&](int trait){int revealed=R.knowledge<60?2:R.knowledge<85?5:10;if(trait>=revealed)return 50;Rng r((uint64_t)(unsigned)p.id*1337+trait*53);return limit(personalityTrait(R.traits,trait)+r.range(-1,1)*(100-R.scoutQuality)/12);};int value=style==DP_YOUNG||style==DP_ACADEMY?(estimated(PT_PROFESSIONALISM)+estimated(PT_AMBITION))/2:style==DP_KEEP||style==DP_LOCAL?(estimated(PT_LOYALTY)+estimated(PT_LEADERSHIP)+estimated(PT_CONSISTENCY))/3:(estimated(PT_COMPOSURE)+estimated(PT_BIG_MATCH)+estimated(PT_CONSISTENCY))/3;return (value-50)*std::min(80,R.knowledge)/200;}
int personalityLegendBonus(const Career& K,int pid,int club){if(!K.personalityEnabled())return 0;auto it=K.personalities.players.find(pid);auto R=relation(K,pid,club);if(it==K.personalities.players.end()||!R||R->seasons<3)return 0;auto& P=it->second.traits;return std::clamp(R->attachment+R->fanPopularity+(P.loyalty+P.leadership)/2+(R->captaincy?30:0),0,250);}
float personalityStressMultiplier(const PlayerPersonality& P){return std::clamp(1.f+(50-P.composure)*.002f+(50-P.bigMatchTemperament)*.0005f,.87f,1.13f);}
float personalityFoulMultiplier(const PlayerPersonality& P){return std::clamp(1.f+(P.aggression-50)*.002f-(P.composure-50)*.001f-(P.professionalism-50)*.001f,.88f,1.12f);}
bool personalityBigMatch(const Career& K,const MatchRes& M,const Competition* C){if(M.decisive||C&&(C->kind==3||C->kind==7||C->kind==8||C->format==FMT_SINGLE))return true;if(clubOk(M.home)&&clubOk(M.away)&&supporterDistance(M.home,M.away)<30)return true;if(C&&C->format==FMT_LEAGUE&&K.season.now>29){auto tab=C->table(0,0);for(int i=0;i<(int)tab.size();i++)if((tab[i].team==M.home||tab[i].team==M.away)&&(i<3||i>=(int)tab.size()-3))return true;}return false;}
bool personalityBigMatch(const Career& K,int ci,int mi){return ci>=0&&ci<(int)K.season.comps.size()&&mi>=0&&mi<(int)K.season.comps[ci].matches.size()&&personalityBigMatch(K,K.season.comps[ci].matches[mi],&K.season.comps[ci]);}
float personalityMatchMultiplier(Career& K,const Player& p,int club,int key,bool important,float pressure){if(!K.personalityEnabled()||!clubOk(club))return 1;auto& P=K.personalityPlayer(p,club);auto& R=K.personalityRelation(P,club);Rng r((uint64_t)(unsigned)p.id*0xAAB13577ULL^((uint64_t)K.year<<32)^(unsigned)key);float variation=r.frange(-1,1)*(100-P.traits.consistency)*.0003f*(1+(100-R.adaptationProgress)*.002f);float stress=(pressure*.002f+(important?.006f:0))*((50-P.traits.composure)/50.f)*(1-P.traits.leadership*.003f);float big=important?(P.traits.bigMatchTemperament-50)*.00008f:0;float adaptation=R.adaptationProgress<100?(100-R.adaptationProgress)*.00005f:0;return std::clamp(1+variation-stress+big-adaptation,.955f,1.04f);}
float personalityTeamMultiplier(Career& K,int club,const MatchRes& M,const Competition* C){if(!K.personalityEnabled()||!clubOk(club)||!g_world.teams[club].squadGen)return 1;bool big=personalityBigMatch(K,M,C);auto xi=g_world.pickLineup(club,g_world.teams[club].formation,RULESET_CAREER);float sum=0;int n=0;for(int i=0;i<11&&i<(int)xi.size();i++)if(xi[i]>=0){sum+=personalityMatchMultiplier(K,g_world.teams[club].squad[xi[i]],club,(int)(K.season.now*1000)+M.home*31+M.away,big,.5f);n++;}return n?sum/n:1;}
namespace {
template<class T>void vectorIO(Writer& w,std::vector<T>& v){w.vpod(v);}
template<class T>void vectorIO(Reader& r,std::vector<T>& v){unsigned n=0;r.pod(n);long pos=ftell(r.f);fseek(r.f,0,SEEK_END);long end=ftell(r.f);fseek(r.f,pos,SEEK_SET);if(!r.ok||n>2000000||pos<0||end<pos||(uint64_t)n*sizeof(T)>(uint64_t)(end-pos)){r.ok=false;return;}v.resize(n);if(n&&fread(v.data(),sizeof(T),n,r.f)!=n)r.ok=false;}
template<class IO>void recordIO(IO& io,PersonalityPlayer& P){io.pod(P.pid);io.pod(P.activeClub);io.pod(P.retired);io.pod(P.knowledge);io.pod(P.scoutQuality);io.pod(P.lastYear);io.pod(P.lastAge);io.pod(P.name);io.pod(P.traits);vectorIO(io,P.relations);vectorIO(io,P.events);}
}
void personalitySave(Writer& w,const Career& K){w.pod(K.personalities.matchYear);w.vpod(K.personalities.matches);unsigned n=(unsigned)K.personalities.players.size();w.pod(n);for(auto& pair:K.personalities.players)recordIO(w,const_cast<PersonalityPlayer&>(pair.second));}
void personalityLoad(Reader& r,Career& K){if(getenv("FOOT_PERSONALITY_DEBUG"))fprintf(stderr,"Personality input valid=%d position=%ld\n",r.ok,ftell(r.f));K.personalities=PersonalityState();r.pod(K.personalities.matchYear);vectorIO(r,K.personalities.matches);unsigned n=0;r.pod(n);if(!r.ok||n>2000000){r.ok=false;return;}auto& ledger=K.personalities.matches;if(!std::is_sorted(ledger.begin(),ledger.end())||std::adjacent_find(ledger.begin(),ledger.end())!=ledger.end())r.ok=false;for(unsigned i=0;i<n&&r.ok;i++){PersonalityPlayer P;recordIO(r,P);if(!r.ok)break;P.name[79]=0;if(P.pid<=0||P.activeClub< -1||P.activeClub>=(int)g_world.teams.size()||P.retired<0||P.retired>1||P.knowledge<0||P.knowledge>100||P.scoutQuality<0||P.scoutQuality>100||P.relations.size()>80||P.events.size()>60||K.personalities.players.count(P.pid)){r.ok=false;break;}for(int t=0;t<10;t++)if(personalityTrait(P.traits,t)<0||personalityTrait(P.traits,t)>100)r.ok=false;std::set<int> clubs;for(auto& R:P.relations){if(!clubOk(R.clubId)||!clubs.insert(R.clubId).second||R.mentorPid<0||R.mentorPid==P.pid||R.temporary<0||R.temporary>1)r.ok=false;for(int v:{R.attachment,R.fanPopularity,R.managerRelationship,R.squadInfluence,R.adaptationProgress})if(v<0||v>100)r.ok=false;}for(auto& e:P.events){e.text[159]=0;if(e.club< -1||e.club>=(int)g_world.teams.size()||e.type<0||e.type>10)r.ok=false;}if(!r.ok&&getenv("FOOT_PERSONALITY_DEBUG"))fprintf(stderr,"Rejected pid=%d active=%d relations=%zu events=%zu\n",P.pid,P.activeClub,P.relations.size(),P.events.size());if(r.ok)K.personalities.players.emplace(P.pid,std::move(P));}}
