#include <cmath>
#include "game.h"
#include "match.h"
#include "serial.h"
#include "packio.h"
#include <cstring>
#include <set>
#include <limits>
namespace {
template<size_t N> void text(char(&dst)[N],const std::string& value){snprintf(dst,N,"%s",value.c_str());}
int bound(int value){return std::clamp(value,0,100);}
bool clubValid(int t){return t>=0&&t<(int)g_world.teams.size()&&g_world.teams[t].kind==TK_CLUB&&!g_world.teams[t].freeAgents&&g_world.teams[t].youth!=8;}
uint64_t key(int ci,int mi){return (uint64_t)(unsigned)ci<<32|(unsigned)mi;}
bool once(std::vector<uint64_t>& ledger,uint64_t k){auto at=std::lower_bound(ledger.begin(),ledger.end(),k);if(at!=ledger.end()&&*at==k)return false;ledger.insert(at,k);return true;}
int capacity(int club){auto& T=g_world.teams[club];return T.sta.init&&T.sta.capacity()>0?T.sta.capacity():T.kind==TK_NATION?60000:T.status==CS_PRO?20000:T.status==CS_SEMIPRO?3000:500;}
void populations(SupporterProfile& P){P.totalSupporters=std::clamp(P.totalSupporters,50,20000000);int remaining=std::max(0,P.totalSupporters-P.seasonTicketHolders);P.activeCore=std::min(remaining,P.totalSupporters*(5+P.fervor/10)/100);remaining-=P.activeCore;P.historical=std::min(remaining,P.totalSupporters*P.loyalty/250);remaining-=P.historical;P.international=std::min(remaining,P.expectations<65?0:P.totalSupporters*(P.expectations-60)/100);P.casual=remaining-P.international;}
SupporterProfile initial(int club,int year,int tier){auto& T=g_world.teams[club];Rng r(T.seed^0xFA93A581ULL);SupporterProfile P;P.clubId=club;int cap=capacity(club);int reputation=teamReputation(club);P.totalSupporters=(int)std::clamp(std::max(50,T.sta.fans)*(tier<=1?3.0+reputation/15.0:1.0+reputation/100.0),50.0,20000000.0);if(T.kind==TK_NATION)P.totalSupporters=cap*3;if(T.parent>=0||T.youth&&T.youth!=6)P.totalSupporters=std::min(P.totalSupporters,std::max(50,cap/4));P.loyalty=r.range(55,85);P.fervor=r.range(40,85);P.patience=r.range(45,85);P.localIdentity=tier>=5?85:r.range(45,80);P.expectations=bound(reputation/2+(tier<=1?25:tier<=4?10:0)+(int)T.honours.size()*2);P.seasonTicketCapacity=cap*70/100;P.seasonTicketHolders=std::min(P.seasonTicketCapacity,P.totalSupporters/5);P.seasonYear=year;P.recordAttendance=std::max(0,T.sta.bestAtt);P.knownCapacity=cap;P.knownPrice=supporterPrice(club);P.lastTier=tier;text(P.knownStadium,T.stadium);text(P.knownTown,T.town);populations(P);return P;}
const SupporterGate* gate(const SupporterProfile& P,int year,int ci,int mi){for(auto& g:P.gates)if(g.year==year&&g.comp==ci&&g.match==mi)return &g;return nullptr;}
void rivalry(SupporterProfile& P,int other,int intensity,int type,int year){if(other<0||other==P.clubId)return;   // jamais rival de soi-même (rejetait la sauvegarde au chargement)
 for(auto& R:P.rivalries)if(R.clubId==other){R.intensity=std::max(R.intensity,intensity);R.meetings++;if(R.type==RV_RECENT&&R.meetings>=3)R.type=RV_SPORTING;if(R.meetings>=10&&R.lastYear<year&&R.type==RV_LOCAL)R.type=RV_HISTORICAL;R.lastYear=year;return;}if(P.rivalries.size()<16){SupporterRivalry R;R.clubId=other;R.intensity=intensity;R.type=type==RV_SPORTING?RV_RECENT:type;R.meetings=1;R.lastYear=year;P.rivalries.push_back(R);}}
}
const char* supporterAtmosphereName(int value,int protest){if(protest>=2)return "HOSTILE";return value<20?"CALME":value<40?"CORRECTE":value<60?"CHAUDE":value<80?"TRÈS CHAUDE":"BOUILLANTE";}
const char* supporterChantName(int state){static const char* names[]={"CHANTS","CHANTS FORTS","ENCOURAGEMENTS","SILENCE TENDU","SIFFLETS","CÉLÉBRATION","CONTESTATION"};return names[std::clamp(state,0,6)];}
const char* supporterEventName(int type){static const char* names[]={"TIFO","CONTESTATION","BOYCOTT","FÊTE DU TITRE","FÊTE DE LA MONTÉE","HOMMAGE","RECORD D'AFFLUENCE","RETOUR D'UNE LÉGENDE","PREMIER MATCH DU STADE","PUBLIC HOSTILE","ABONNEMENTS","RELÉGATION"};return names[std::clamp(type,0,11)];}
int supporterDistance(int a,int b){if(a<0||b<0||a>=(int)g_world.teams.size()||b>=(int)g_world.teams.size())return 900;auto& A=g_world.teams[a];auto& B=g_world.teams[b];if(a==b)return 0;if(!A.town.empty()&&A.town==B.town)return 15;if(A.district>=0&&A.district==B.district)return 35+(A.seed^B.seed)%50;if(A.dept>=0&&A.dept==B.dept)return 70+(A.seed^B.seed)%80;if(A.region>=0&&A.region==B.region)return 160+(A.seed^B.seed)%150;return (A.nation==B.nation?420:950)+(A.seed^B.seed)%200;}
int supporterPrice(int club){auto& S=g_world.teams[club].sta;int64_t total=0,seats=0;for(auto& stand:S.s){total+=(int64_t)stand.seats*stand.price;seats+=stand.seats;}return seats?std::max(1,(int)(total/seats)):g_world.teams[club].status==CS_PRO?25:3;}
bool Career::supportersEnabled()const{return kind==CK_CLUB&&!opts.lite&&!euroOnly;}
SupporterProfile& Career::supportersProfile(int club){auto at=supporters.profiles.find(club);if(at==supporters.profiles.end())at=supporters.profiles.emplace(club,initial(club,year,g_world.teams[club].lastTier>=0?g_world.teams[club].lastTier:8)).first;return at->second;}
void Career::supportersInit(){if(!supportersEnabled())return;std::vector<int> tiers(g_world.teams.size(),8),homeGames(g_world.teams.size(),17);for(auto& P:pyramids)for(auto& pool:P.pools){for(int t:pool.clubs)if(t>=0&&t<(int)tiers.size())tiers[t]=pool.tier;for(auto& group:pool.groups)for(int t:group)if(t>=0&&t<(int)homeGames.size())homeGames[t]=std::max(1,(int)group.size()-1);}std::map<std::pair<int,int>,int> nearby;for(int t=0;t<(int)g_world.teams.size();t++)if(clubValid(t)){auto& T=g_world.teams[t];auto at=supporters.profiles.find(t);if(at==supporters.profiles.end())at=supporters.profiles.emplace(t,initial(t,year,tiers[t])).first;at->second.homeGames=homeGames[t];if(T.parent<0&&(!T.youth||T.youth==6)&&T.district>=0){auto geo=std::make_pair(T.nation,T.district);auto last=nearby.find(geo);if(last!=nearby.end()&&last->second!=t&&at->second.rivalries.empty()){rivalry(at->second,last->second,35,RV_LOCAL,year);rivalry(supporters.profiles[last->second],t,35,RV_LOCAL,year);}nearby[geo]=t;}}supporters.initialized=1;}
void Career::supportersEvent(int club,int type,const std::string& reason,int intensity,int duration,int ci,int mi,int pid){if(!supportersEnabled()||!clubValid(club))return;auto& P=supportersProfile(club);for(auto& old:P.supporterEvents)if(old.year==year&&old.type==type&&old.relatedComp==ci&&old.relatedMatch==mi&&old.relatedPlayer==pid&&std::string(old.reason)==reason)return;SupporterEvent e;e.type=type;e.year=year;e.date=season.now;e.intensity=bound(intensity);e.duration=duration;e.relatedComp=ci;e.relatedMatch=mi;e.relatedPlayer=pid;text(e.reason,reason);P.supporterEvents.push_back(e);if(P.supporterEvents.size()>120)P.supporterEvents.erase(P.supporterEvents.begin());if(club==userTeam)season.news.push_back("[Supporters] "+reason);bool major=type!=SU_SUBSCRIPTIONS&&type!=SU_PROTEST&&type!=SU_HOSTILE&&type!=SU_RECORD_ATTENDANCE;auto h=clubHistories.find(club);if(major&&(h!=clubHistories.end()||club==userTeam)){museumState(club);MuseumEvent m;m.year=year;m.time=season.now;m.category=type==SU_RECORD_ATTENDANCE?MH_RECORD:type==SU_TITLE_PARTY?MH_TROPHY:type==SU_PROMOTION_PARTY||type==SU_RELEGATION?MH_MOVE:MH_ALL;text(m.text,std::string(supporterEventName(type))+" : "+reason);auto& H=clubHistories[club];H.timeline.push_back(m);}}
int supporterFanPopularity(const Career& K,int club,int pid){
 if(club<0||club>=(int)g_world.teams.size())return 0;int social=0;auto pp=K.personalities.players.find(pid);if(K.personalityEnabled()&&pp!=K.personalities.players.end())for(auto& R:pp->second.relations)if(R.clubId==(g_world.teams[club].parent>=0?g_world.teams[club].parent:club))social=bound(R.fanPopularity+(pp->second.traits.loyalty+pp->second.traits.leadership-100)/10+R.attachment/10);
 auto it=K.supporters.profiles.find(club);if(it!=K.supporters.profiles.end())for(auto& p:it->second.players)if(p.pid==pid)return std::max(social,p.value);auto& T=g_world.teams[club];auto at=std::find_if(T.squad.begin(),T.squad.end(),[&](auto& p){return p.id==pid;});if(at==T.squad.end())return social;auto& P=*at;int value=15+std::min(25,(int)P.apps)+std::min(25,(int)P.goals*2)+(pid==T.captainPid?20:0)+(P.nation==T.nation?5:0);auto H=K.clubHistories.find(club);if(H!=K.clubHistories.end())for(auto& h:H->second.players)if(h.pid==pid)value+=std::min(35,h.seasons*5+h.apps/15)+(h.hall?20:0);return std::max(social,bound(value));
}
MatchAtmosphere supportersMatchAtmosphere(Career* K,int home,int away,int ci,int mi,int weather,bool neutral){MatchAtmosphere A;if(home<0||away<0||home>=(int)g_world.teams.size()||away>=(int)g_world.teams.size())return A;bool full=K&&K->supportersEnabled()&&clubValid(home)&&clubValid(away);SupporterProfile fallbackHome=initial(home,K?K->year:2026,g_world.teams[home].lastTier>=0?g_world.teams[home].lastTier:8),fallbackAway=initial(away,K?K->year:2026,g_world.teams[away].lastTier>=0?g_world.teams[away].lastTier:8);fallbackHome.seasonTicketHolders=0;const SupporterProfile& h=full?K->supportersProfile(home):fallbackHome;const SupporterProfile& a=full?K->supportersProfile(away):fallbackAway;if(full){if(auto* g=gate(h,K->year,ci,mi)){A.attendance=g->attendance;A.visitors=g->visitors;A.index=g->index;A.chant=g->chant;A.tifo=g->tifo;A.distance=supporterDistance(home,away);for(auto& R:h.rivalries)if(R.clubId==away)A.rivalry=R.intensity;A.homeEffect=neutral?0:g->index*.00003f;A.awayPressure=neutral?0:g->index/100.f;return A;}}
 int cap=capacity(home);if(neutral)cap=std::max(cap,40000);A.distance=supporterDistance(home,away);for(auto& R:h.rivalries)if(R.clubId==away)A.rivalry=R.intensity;if(A.distance<90&&g_world.teams[home].nation==g_world.teams[away].nation)A.rivalry=std::max(A.distance<30?60:35,A.rivalry);double important=1.0;int ko=-1;bool final=false,europe=false;int tier=h.lastTier;int race=0;if(K&&ci>=0&&ci<(int)K->season.comps.size()&&mi>=0&&mi<(int)K->season.comps[ci].matches.size()){auto& C=K->season.comps[ci];auto& M=C.matches[mi];important+=C.format!=FMT_LEAGUE?.15:0;final=C.format==FMT_SINGLE||M.neutral&&M.decisive||M.decisive&&C.matches.size()<8;europe=C.kind==3||C.kind==7||C.kind==8;important+=final?.35:europe?.25:0;ko=kickoffMinutes(ci,mi);if(C.format==FMT_LEAGUE&&K->season.now>29){auto table=C.table(0,0);for(int i=0;i<(int)table.size();i++)if(table[i].team==home){race=i<3||i>=(int)table.size()-3?15:0;break;}}}
 int visitorCap=cap*(tier>=5?15:5)/100;double travel=a.activeCore*(1+A.rivalry/80.0)*important/(1+A.distance/180.0)*(a.sportingSatisfaction/160.0+.55);if(ko>=0&&ko/1440%7<5)travel*=.8;A.visitors=std::min(visitorCap,std::max(0,(int)travel));double ref=cap>=20000?25:cap>=8000?15:cap>=3000?8:cap>=1000?5:3;double price=std::clamp(std::exp(-.8*(supporterPrice(home)/ref-1)),.12,1.35);double weatherFactor=weather>=3?.65:weather==2?.84:1.0;double form=.65+h.sportingSatisfaction/180.0+h.loyalty/500.0;double prestige=std::clamp(1+(g_world.teams[away].rating-g_world.teams[home].rating)*.007,.8,1.3);double day=ko>=0&&ko/1440%7<5?.93:1.0;double base=std::min((double)h.totalSupporters,(double)cap*(.45+h.loyalty/150.0));double demand=base*form*prestige*important*price*weatherFactor*day*(1+A.rivalry/240.0+race/180.0);demand=std::max(demand,h.seasonTicketHolders*(.75+h.loyalty/500.0));if(h.boycottMatches>0)demand*=h.protestLevel==5?.4:.7;if(h.firstStadiumPending||h.celebrationPending)demand*=1.15;A.attendance=std::clamp((int)demand+A.visitors,0,cap);A.visitors=std::min(A.visitors,A.attendance);A.index=bound((int)(A.attendance*45LL/std::max(1,cap)+h.fervor*.35+A.rivalry*.12+(important-1)*20));if(h.boycottMatches>0)A.index=std::max(5,A.index-30);A.chant=h.protestLevel>=2?CH_PROTEST:h.lossStreak>=3&&h.sportingSatisfaction<35?CH_WHISTLES:h.sportingSatisfaction<35?CH_TENSE:A.index>70?CH_LOUD:CH_NORMAL;
 bool anniversary=g_world.teams[home].founded>0&&K&&(K->year-g_world.teams[home].founded)%10==0&&h.seasonMatches==0;A.tifo=h.firstStadiumPending?7:h.celebrationPending==1?5:h.celebrationPending==2?6:h.celebrationPending==3?4:A.rivalry>=55?1:final?2:anniversary?3:europe&&!h.firstEuropean?8:A.index>85&&important>1.25?9:-1;if(h.fervor<40&&A.tifo<5)A.tifo=-1;A.homeEffect=neutral?0:A.index*.00003f;A.awayPressure=neutral?0:A.index/100.f;return A;}
void Career::supportersPrepareMatch(int ci,int mi,int weather){if(!supportersEnabled()||ci<0||ci>=(int)season.comps.size()||mi<0||mi>=(int)season.comps[ci].matches.size())return;auto& M=season.comps[ci].matches[mi];if(!clubValid(M.home)||!clubValid(M.away))return;auto& H=supportersProfile(M.home);if(H.seasonYear!=year){H.seasonYear=year;H.seenMatches.clear();H.seenAttendance.clear();H.preparedMatches.clear();H.bookedMoney.clear();H.gates.clear();}if(!once(H.preparedMatches,key(ci,mi)))return;supportersOnTicketPriceChange(M.home);supportersOnStadiumChange(M.home);if(weather<0){int month=(int)(season.now/4.2);weather=month>=3&&month<=7?((ci*31+mi*7+year)%4==0?2:1):0;}auto A=supportersMatchAtmosphere(this,M.home,M.away,ci,mi,weather,M.neutral);SupporterGate G;G.year=year;G.comp=ci;G.match=mi;G.attendance=A.attendance;G.visitors=A.visitors;G.index=A.index;G.chant=A.chant;G.tifo=A.tifo;H.gates.push_back(G);H.lastAttendance=A.attendance;H.lastVisitors=A.visitors;H.atmosphereIndex=A.index;H.lastChant=A.chant;H.lastTifo=A.tifo;if(A.rivalry>0){rivalry(H,M.away,A.rivalry,RV_LOCAL,year);rivalry(supportersProfile(M.away),M.home,A.rivalry,RV_LOCAL,year);}if(A.chant==CH_PROTEST)supportersEvent(M.home,SU_HOSTILE,"Accueil hostile envers la direction dans une crise prolongée.",A.index,1,ci,mi);if(A.tifo==8)H.firstEuropean=1;if(A.tifo>=0){static const char* reasons[]={"","Derby : le public prépare un tifo.","Un grand tifo pour la finale.","Tifo anniversaire du club.","Hommage à un joueur emblématique.","Tifo pour célébrer le titre.","Tifo pour célébrer la montée.","Premier match du nouveau stade.","Premier rendez-vous européen de la saison.","Un rendez-vous historique pour les tribunes."};supportersEvent(M.home,SU_TIFO,reasons[A.tifo],A.index,1,ci,mi);}if(H.firstStadiumPending){supportersEvent(M.home,SU_FIRST_STADIUM,"Premier match dans le stade rénové / nouveau : "+g_world.teams[M.home].stadium,A.index,1,ci,mi);H.firstStadiumPending=0;}H.celebrationPending=0;}
int supportersLiveChant(const MatchSetup& S,int hg,int ag,float minute){if(S.training)return CH_TENSE;int base=S.supporterChant;if(hg-ag>=2||hg>ag&&minute>=88)return CH_CELEBRATE;
 // sifflets et contestation par vagues (entrée des joueurs, quelques minutes de temps en temps, avant la pause, fin de match), pas pendant tout le match
 float ph=std::fmod(minute+((S.home*7+S.away*3)%9),17.f);bool wave=minute<3.f||(ph>=9.f&&ph<11.5f)||(minute>=44.f&&minute<46.f)||minute>=88.f;
 if((ag-hg>=3&&S.supporterPatience<45||ag-hg>=4)&&minute>=55)return wave?CH_WHISTLES:CH_TENSE;if(base==CH_PROTEST||base==CH_WHISTLES)return wave?base:CH_TENSE;if(base==CH_TENSE)return base;if(hg<ag&&minute>65)return S.supporterLoyalty>65?CH_ENCOURAGE:CH_TENSE;return base;}
void supportersApplySetup(Career* K,MatchSetup& S,int ci,int mi){S.personalityActive=K&&K->personalityEnabled()&&!S.training;S.personalityImportant=S.personalityActive&&personalityBigMatch(*K,ci,mi);S.personalityKey=ci*100000+mi;if(S.training)return;if(K&&K->supportersEnabled())K->supportersPrepareMatch(ci,mi,S.weather);auto A=supportersMatchAtmosphere(K,S.home,S.away,ci,mi,S.weather,S.neutral);S.attendance=A.attendance;int cap=S.neutral?std::max(capacity(S.home),40000):capacity(S.home);S.crowdFill=A.attendance/(float)std::max(1,cap);S.supporterAtmosphere=A.index;S.supporterChant=A.chant;S.supporterTifo=A.tifo;S.supporterVisitors=A.visitors;S.supporterPressure=A.awayPressure;S.homeBoost=std::min(.04f,S.homeBoost+A.homeEffect);if(K&&K->supportersEnabled()&&clubValid(S.home)){auto& P=K->supportersProfile(S.home);S.supporterLoyalty=P.loyalty;S.supporterPatience=P.patience;}else{S.supporterLoyalty=65;S.supporterPatience=65;}}
void Career::supportersOnMatchEnd(int ci,int mi){if(!supportersEnabled()||ci<0||ci>=(int)season.comps.size()||mi<0||mi>=(int)season.comps[ci].matches.size())return;auto& M=season.comps[ci].matches[mi];if(!M.played||!clubValid(M.home)||!clubValid(M.away))return;supportersPrepareMatch(ci,mi);auto& H=supportersProfile(M.home);auto* G=gate(H,year,ci,mi);if(G&&!M.neutral&&once(H.seenAttendance,key(ci,mi))){if(M.home==userTeam||clubHistories.count(M.home))museumAttendance(ci,mi,G->attendance);H.seasonMatches++;H.seasonAttendance+=G->attendance;H.seasonBest=std::max(H.seasonBest,G->attendance);H.seasonWorst=H.seasonMatches==1?G->attendance:std::min(H.seasonWorst,G->attendance);if(G->attendance>H.recordAttendance){H.recordAttendance=G->attendance;H.recordYear=year;H.recordDate=season.now;H.recordOpponent=M.away;H.recordComp=ci;H.recordMatch=mi;text(H.recordCompetition,season.comps[ci].name);text(H.recordOpponentName,g_world.teams[M.away].name);text(H.recordDateText,kickoffText(ci,mi,true));supportersEvent(M.home,SU_RECORD_ATTENDANCE,fmt("Record : %d spectateurs contre %s (%s).",G->attendance,g_world.teams[M.away].name.c_str(),season.comps[ci].name.c_str()),G->index,0,ci,mi);}}
 for(int side=0;side<2;side++){int club=side?M.away:M.home;auto& P=supportersProfile(club);if(!once(P.seenMatches,key(ci,mi)))continue;int gf=side?M.ag:M.hg,ga=side?M.hg:M.ag;bool win=gf>ga||(gf==ga&&M.ph>=0&&(side?M.pa>M.ph:M.ph>M.pa)),loss=gf<ga||(gf==ga&&M.ph>=0&&(side?M.pa<M.ph:M.ph<M.pa));P.lossStreak=loss?P.lossStreak+1:0;P.winStreak=win?P.winStreak+1:0;int reaction=win?2:loss?-2:0;if(P.lossStreak>=3)reaction-=2;if(P.loyalty>75&&reaction<0)reaction++;P.sportingSatisfaction=bound(P.sportingSatisfaction+reaction);P.managerTrust=bound(P.managerTrust+reaction);if(win&&P.winStreak>=4)P.totalSupporters+=std::max(1,P.totalSupporters/400);if(P.lossStreak>=6)P.totalSupporters=std::max(50,P.totalSupporters-P.totalSupporters*(100-P.loyalty)/10000);if(club==userTeam){if(mgr.budget<0)P.boardTrust=bound(P.boardTrust-2);if(sportingMode()&&sporting.employed){P.transferTrust=bound((P.transferTrust*4+sporting.coachTrust)/5);P.managerTrust=bound((P.managerTrust*4+sporting.coachTrust)/5);}}bool unhappy=P.sportingSatisfaction<35||P.boardTrust<30||P.transferTrust<25;P.crisisMatches=unhappy?P.crisisMatches+1:std::max(0,P.crisisMatches-2);int target=P.crisisMatches<3?0:P.crisisMatches<6?1:P.crisisMatches<10?2:P.crisisMatches<14?3:4;if(P.patience>70)target=std::max(0,target-1);if(!unhappy&&P.protestLevel>0)P.protestLevel--;else if(target>P.protestLevel){P.protestLevel=target;supportersEvent(club,SU_PROTEST,"La contestation monte progressivement dans les tribunes.",target*18,2,ci,mi);}if(P.boycottMatches>0&&club==M.home){P.boycottMatches--;if(P.boycottMatches==0){P.protestLevel=std::min(P.protestLevel,3);P.seriousTrigger=0;supportersEvent(club,SU_PROTEST,"Fin du boycott : retour progressif du public.",40);}}
 if(P.boycottMatches==0&&P.seriousTrigger&&P.boardTrust<15&&P.sportingSatisfaction<20&&P.patience<35&&P.crisisMatches>=12){P.protestLevel=5;P.boycottMatches=2;supportersEvent(club,SU_BOYCOTT,"Boycott exceptionnel annoncé pour deux rencontres à domicile.",90,2,ci,mi);}else if(P.boycottMatches==0&&P.protestLevel==4&&P.seriousTrigger&&P.crisisMatches>=16){P.boycottMatches=1;supportersEvent(club,SU_BOYCOTT,"Boycott partiel annoncé pour le prochain match à domicile.",65,1,ci,mi);}int opponent=side?M.home:M.away;if(M.decisive&&std::abs(gf-ga)<=1)rivalry(P,opponent,45,RV_SPORTING,year);for(auto& R:P.rivalries)if(R.clubId==opponent&&R.meetings>=3)R.intensity=bound(R.intensity+2);for(auto& player:g_world.teams[club].squad){auto it=std::find_if(P.players.begin(),P.players.end(),[&](auto p){return p.pid==player.id;});if(it==P.players.end()){SupporterPopularity popular;popular.pid=player.id;popular.value=supporterFanPopularity(*this,club,player.id);P.players.push_back(popular);it=P.players.end()-1;}if(it->lastYear!=year){it->lastYear=year;it->seenApps=it->seenGoals=0;it->seasons++;}it->value=bound(it->value+std::min(3,std::max(0,(int)player.goals-it->seenGoals)*2)+(player.id==g_world.teams[club].captainPid&&win?1:0));it->seenApps=player.apps;it->seenGoals=player.goals;}if(P.players.size()>180)P.players.erase(P.players.begin(),P.players.begin()+P.players.size()-180);populations(P);g_world.teams[club].sta.fans=P.totalSupporters;}}
void Career::supportersOnTicketPriceChange(int club){if(!supportersEnabled()||!clubValid(club))return;auto& P=supportersProfile(club);int price=supporterPrice(club);if(price==P.knownPrice)return;if(price>P.knownPrice*12/10){P.boardTrust=bound(P.boardTrust-8);supportersEvent(club,SU_PROTEST,"La hausse du prix des billets inquiète les supporters.",45);if(price>P.knownPrice*15/10){P.seriousTrigger=1;P.triggerYear=year;}}else if(price<P.knownPrice)P.boardTrust=bound(P.boardTrust+3);P.knownPrice=price;}
void Career::supportersOnManagerChange(int club,const std::string& name){if(!supportersEnabled()||!clubValid(club))return;auto& P=supportersProfile(club);if(name==P.knownCoach)return;if(P.knownCoach[0]){P.managerTrust=bound(50+P.sportingSatisfaction/8);P.boardTrust=bound(P.boardTrust+(P.sportingSatisfaction<35?3:-2));}text(P.knownCoach,name);}
void Career::supportersOnStadiumChange(int club){if(!supportersEnabled()||!clubValid(club))return;auto& T=g_world.teams[club];auto& P=supportersProfile(club);int cap=capacity(club);bool moved=std::string(P.knownTown)!=T.town,name=std::string(P.knownStadium)!=T.stadium;if(cap!=P.knownCapacity||moved||name){P.firstStadiumPending=1;if(cap>P.knownCapacity){P.totalSupporters+=std::min(P.totalSupporters/20,(cap-P.knownCapacity)/4);P.boardTrust=bound(P.boardTrust+4);}if(moved&&P.localIdentity>70||name&&T.sta.namingIncome>0&&P.localIdentity>75){P.boardTrust=bound(P.boardTrust-10);P.seriousTrigger=1;P.triggerYear=year;supportersEvent(club,SU_PROTEST,moved?"Le déménagement du stade inquiète les supporters locaux.":"Le changement de nom commercial fait débat.",50);}P.knownCapacity=cap;text(P.knownTown,T.town);text(P.knownStadium,T.stadium);P.seasonTicketCapacity=cap*70/100;P.seasonTicketHolders=std::min(P.seasonTicketHolders,P.seasonTicketCapacity);}populations(P);}
void Career::supportersOnTransfer(const Player& player,int from,int to,int fee){if(!supportersEnabled())return;for(auto& l:loans)if(l.pid==player.id)return;if(clubValid(from)&&clubValid(to)){int a=g_world.teams[from].parent>=0?g_world.teams[from].parent:from;int b=g_world.teams[to].parent>=0?g_world.teams[to].parent:to;if(a==b)return;}if(clubValid(from)){auto& P=supportersProfile(from);int popularity=supporterFanPopularity(*this,from,player.id);popularity=std::max(popularity,std::min(100,player.apps/4+player.goals*2+(player.id==g_world.teams[from].captainPid?15:0)));if(popularity>=70){bool successor=false;for(auto& q:g_world.teams[from].squad)if(q.id!=player.id&&q.pos==player.pos&&q.overall()>=player.overall()-5)successor=true;int anger=25-(player.age>=32?10:0)-(fee>=player.value()?6:0)-(player.morale<40?5:0)-(successor?5:0);P.transferTrust=bound(P.transferTrust-std::max(0,anger));P.boardTrust=bound(P.boardTrust-std::max(0,anger)/2);if(anger>=15){P.seriousTrigger=1;P.triggerYear=year;supportersEvent(from,SU_PROTEST,"La vente de "+player.name+" inquiète le public ; prix et succession examinés.",popularity,3,-1,-1,player.id);}}else if(fee>=player.value())P.transferTrust=bound(P.transferTrust+2);}if(clubValid(to)){auto& P=supportersProfile(to);bool former=false;auto H=clubHistories.find(to);if(H!=clubHistories.end())for(auto& h:H->second.players)if(h.pid==player.id&&(h.apps>=50||h.hall))former=true;if(former){P.sportingSatisfaction=bound(P.sportingSatisfaction+10);P.totalSupporters+=std::max(1,P.totalSupporters/50);P.celebrationPending=3;supportersEvent(to,SU_LEGEND_RETURN,"Retour de "+player.name+", une figure appréciée du club.",85,1,-1,-1,player.id);}else{int boost=player.overall()>g_world.teams[to].rating+3?5:player.age<=21&&player.nation==g_world.teams[to].nation?3:1;P.transferTrust=bound(P.transferTrust+boost);if(boost>=3)P.totalSupporters+=std::max(1,P.totalSupporters/200);}populations(P);g_world.teams[to].sta.fans=P.totalSupporters;}}
void Career::supportersCampaign(int club,bool charge){if(!supportersEnabled()||!clubValid(club))return;auto& P=supportersProfile(club);if(P.campaignYear==year)return;int old=P.seasonTicketHolders,cap=capacity(club);P.seasonTicketCapacity=cap*70/100;double ref=cap>=20000?25:cap>=8000?15:cap>=3000?8:cap>=1000?5:3;double price=std::clamp(std::exp(-.7*(supporterPrice(club)/ref-1)),.15,1.35);double retained=old*(.50+P.loyalty/200.0+P.sportingSatisfaction/800.0);double newDemand=P.totalSupporters*(.02+P.fervor/1800.0+P.sportingSatisfaction/2300.0);int requests=std::max(0,(int)((retained+newDemand)*price));if(P.firstStadiumPending||P.celebrationPending)requests=requests*110/100;P.seasonTicketHolders=std::min({requests,P.seasonTicketCapacity,P.totalSupporters});P.waitingList=std::max(0,requests-P.seasonTicketCapacity);P.campaignYear=year;int homeMatches=std::max(1,P.homeGames);int64_t gross=(int64_t)P.seasonTicketHolders*supporterPrice(club)*homeMatches*70/100;P.subscriptionEuros=gross;bool own=club==userTeam&&(!sportingMode()||sporting.employed);if(charge&&own){int64_t net=gross*1000/1055*95/100;mgr.budget+=net/1000;mgr.seasonIncome+=net/1000;mgr.seasonGate+=net/1000;}populations(P);supportersEvent(club,SU_SUBSCRIPTIONS,fmt("Campagne : %d abonnés, %d demandes en attente (capacité %d).",P.seasonTicketHolders,P.waitingList,P.seasonTicketCapacity),bound(P.seasonTicketHolders*100/std::max(1,P.seasonTicketCapacity)));}
void Career::supportersStartSeason(){if(!supportersEnabled())return;supportersInit();for(auto& pair:supporters.profiles){auto& P=pair.second;if(P.seasonYear!=year){P.seasonYear=year;P.seasonMatches=P.seasonAttendance=P.seasonBest=P.seasonWorst=0;P.seenMatches.clear();P.seenAttendance.clear();P.preparedMatches.clear();P.bookedMoney.clear();P.gates.clear();for(auto& p:P.players)p.seenApps=p.seenGoals=0;}supportersOnStadiumChange(pair.first);supportersCampaign(pair.first);}if(clubValid(userTeam))supportersOnManagerChange(userTeam,managerName);}
void Career::supportersOnPromotion(int club,int tier){if(!supportersEnabled()||!clubValid(club))return;auto& P=supportersProfile(club);int old=P.lastTier;if(tier<0)return;P.lastTier=tier;if(old<0||old==tier)return;if(tier<old){P.totalSupporters+=std::max(1,P.totalSupporters*(tier<=2?10:7)/100);P.sportingSatisfaction=bound(P.sportingSatisfaction+15);P.fervor=bound(P.fervor+5);P.boardTrust=bound(P.boardTrust+10);P.celebrationPending=2;int crowd=std::max(25,P.totalSupporters*(15+P.fervor/4)/100);supportersEvent(club,SU_PROMOTION_PARTY,fmt("Fête de la montée : %d supporters. Tour du stade, présentation de l'équipe et réception officielle.",crowd),bound(55+P.fervor/3),1);}else{P.totalSupporters=std::max(50,P.totalSupporters-P.totalSupporters*(100-P.loyalty)/500);P.sportingSatisfaction=bound(P.sportingSatisfaction-12);P.boardTrust=bound(P.boardTrust-6);P.seriousTrigger=1;P.triggerYear=year;supportersEvent(club,SU_RELEGATION,"La relégation pèse sur le public ; les fidèles restent présents.",65);}populations(P);g_world.teams[club].sta.fans=P.totalSupporters;}
void Career::supportersOnTitle(int club,int ci){if(!supportersEnabled()||!clubValid(club)||ci<0||ci>=(int)season.comps.size())return;auto& C=season.comps[ci];if(C.kind==12||C.name.find("Amical")!=std::string::npos)return;auto& P=supportersProfile(club);for(auto& e:P.supporterEvents)if(e.year==year&&e.type==SU_TITLE_PARTY&&e.relatedComp==ci)return;int importance=C.kind==3?95:C.kind==7||C.kind==8?85:C.kind==2?80:teamLevel(club)<=2?75:teamLevel(club)<=6?60:45;P.totalSupporters+=std::max(1,P.totalSupporters*importance/1200);P.sportingSatisfaction=bound(P.sportingSatisfaction+10);P.fervor=bound(P.fervor+3);P.managerTrust=bound(P.managerTrust+10);P.celebrationPending=1;int crowd=std::max(25,P.totalSupporters*(10+importance/3)/100);supportersEvent(club,SU_TITLE_PARTY,fmt("%s : %d supporters. Trophée, tour d'honneur, %s et réception officielle.",C.name.c_str(),crowd,importance>=75?"parade en ville":"rassemblement au stade"),importance,1,ci);populations(P);g_world.teams[club].sta.fans=P.totalSupporters;}
void Career::supportersOnSeasonEnd(){if(!supportersEnabled())return;supportersInit();std::vector<int> tiers(g_world.teams.size(),-1);for(auto& P:pyramids)for(auto& pool:P.pools)for(int club:pool.clubs)if(club>=0&&club<(int)tiers.size())tiers[club]=pool.tier;for(int ci=0;ci<(int)season.comps.size();ci++)if(season.comps[ci].done&&season.comps[ci].winner>=0)supportersOnTitle(season.comps[ci].winner,ci);for(auto& pair:supporters.profiles){auto& P=pair.second;if(P.archiveYear==year)continue;P.archiveYear=year;if(tiers[pair.first]>=0)supportersOnPromotion(pair.first,tiers[pair.first]);SupporterAttendance A;A.year=year;A.matches=P.seasonMatches;A.total=P.seasonAttendance;A.best=P.seasonBest;A.worst=P.seasonWorst;A.capacity=capacity(pair.first);A.subscribers=P.seasonTicketHolders;P.attendanceHistory.push_back(A);if(P.attendanceHistory.size()>80)P.attendanceHistory.erase(P.attendanceHistory.begin());int rate=P.sportingSatisfaction>70?2:P.sportingSatisfaction<30?-1:0;P.totalSupporters=std::clamp(P.totalSupporters+P.totalSupporters*rate/100,50,20000000);int reputation=teamReputation(pair.first);P.expectations=bound((P.expectations*3+reputation/2+(P.lastTier<=1?25:P.lastTier<=4?10:0))/4);P.managerTrust=bound((P.managerTrust*3+P.sportingSatisfaction)/4);P.boardTrust=bound(P.boardTrust+(P.sportingSatisfaction>65?2:0)-(pair.first==userTeam&&mgr.budget<0?5:0));if(P.seriousTrigger&&P.triggerYear<year-1)P.seriousTrigger=0;for(auto& R:P.rivalries)if(R.lastYear<year-1)R.intensity=std::max(0,R.intensity-3);int young=0,local=0;for(auto& p:g_world.teams[pair.first].squad){young+=p.age<=21&&p.apps>=5;local+=p.nation==g_world.teams[pair.first].nation&&p.apps>=5;}if(P.localIdentity>70){P.transferTrust=bound(P.transferTrust+std::min(4,young+local/4));}populations(P);g_world.teams[pair.first].sta.fans=P.totalSupporters;}}
int Career::supportersPendingEvent()const{if(!supportersEnabled()||(sportingMode()&&!sporting.employed))return -1;auto it=supporters.profiles.find(userTeam);if(it==supporters.profiles.end())return -1;for(int i=0;i<(int)it->second.supporterEvents.size();i++){auto& e=it->second.supporterEvents[i];if(!e.presented&&(e.type==SU_PROMOTION_PARTY||e.type==SU_TITLE_PARTY))return i;}return -1;}

bool Career::supportersBookGate(int ci,int mi){if(!supportersEnabled())return true;if(ci<0||ci>=(int)season.comps.size()||mi<0||mi>=(int)season.comps[ci].matches.size())return false;auto& M=season.comps[ci].matches[mi];if(M.home!=userTeam||!clubValid(M.home))return false;supportersPrepareMatch(ci,mi);return once(supportersProfile(M.home).bookedMoney,key(ci,mi));}

namespace {
template<class T>void list(Writer& w,std::vector<T>& v){w.vpod(v);}
template<class T>void list(Reader& r,std::vector<T>& v){if(r.packed){r.vpod(v);return;}unsigned n;r.pod(n);if(!r.ok||n>10000){r.ok=false;return;}long pos=ftell(r.f);fseek(r.f,0,SEEK_END);long end=ftell(r.f);fseek(r.f,pos,SEEK_SET);if(pos<0||end<pos||(uint64_t)n*sizeof(T)>(uint64_t)(end-pos)){r.ok=false;return;}v.resize(n);if(n&&fread(v.data(),sizeof(T),n,r.f)!=n)r.ok=false;}
template<class T>void list(PackW& w,std::vector<T>& v){w.vpod(v);}
template<class T>void list(PackR& r,std::vector<T>& v){r.vpod(v,10000);}
template<class IO>void profileIO(IO& io,SupporterProfile& P){
io.pod(P.clubId);io.pod(P.totalSupporters);io.pod(P.seasonTicketHolders);io.pod(P.waitingList);io.pod(P.seasonTicketCapacity);io.pod(P.activeCore);io.pod(P.casual);io.pod(P.historical);io.pod(P.international);io.pod(P.loyalty);io.pod(P.fervor);io.pod(P.expectations);io.pod(P.patience);io.pod(P.localIdentity);io.pod(P.sportingSatisfaction);io.pod(P.managerTrust);io.pod(P.boardTrust);io.pod(P.transferTrust);io.pod(P.atmosphereIndex);io.pod(P.protestLevel);io.pod(P.boycottMatches);io.pod(P.crisisMatches);io.pod(P.lossStreak);io.pod(P.winStreak);io.pod(P.seriousTrigger);io.pod(P.triggerYear);io.pod(P.seasonYear);io.pod(P.campaignYear);io.pod(P.archiveYear);io.pod(P.seasonMatches);io.pod(P.seasonAttendance);io.pod(P.seasonBest);io.pod(P.seasonWorst);io.pod(P.recordAttendance);io.pod(P.recordYear);io.pod(P.recordComp);io.pod(P.recordMatch);io.pod(P.recordOpponent);io.pod(P.recordDate);io.pod(P.lastAttendance);io.pod(P.lastVisitors);io.pod(P.lastChant);io.pod(P.lastTifo);io.pod(P.firstStadiumPending);io.pod(P.celebrationPending);io.pod(P.homeGames);io.pod(P.firstEuropean);io.pod(P.knownCapacity);io.pod(P.knownPrice);io.pod(P.lastTier);io.pod(P.recordCompetition);io.pod(P.recordOpponentName);io.pod(P.recordDateText);io.pod(P.knownStadium);io.pod(P.knownTown);io.pod(P.knownCoach);io.pod(P.subscriptionEuros);
list(io,P.rivalries);list(io,P.attendanceHistory);list(io,P.supporterEvents);list(io,P.gates);list(io,P.players);list(io,P.seenMatches);list(io,P.seenAttendance);list(io,P.preparedMatches);list(io,P.bookedMoney);}
}
// historiques bornés : clubs autres que celui du joueur, événements et popularité des joueurs limités aux plus récents / plus marquants
static void supportersTrim(Career& K){int u=K.userTeam;for(auto& pair:K.supporters.profiles){auto& P=pair.second;bool mine=pair.first==u||(u>=0&&g_world.teams[pair.first].parent==u);
 size_t capEv=mine?120:6,capPl=mine?180:25;
 if(!mine&&P.rivalries.size()>6){std::stable_sort(P.rivalries.begin(),P.rivalries.end(),[](const SupporterRivalry& a,const SupporterRivalry& b){return a.intensity>b.intensity;});P.rivalries.resize(6);}
 if(P.supporterEvents.size()>capEv)P.supporterEvents.erase(P.supporterEvents.begin(),P.supporterEvents.begin()+(P.supporterEvents.size()-capEv));
 if(P.players.size()>capPl){std::stable_sort(P.players.begin(),P.players.end(),[](const SupporterPopularity& a,const SupporterPopularity& b){return a.value>b.value;});P.players.resize(capPl);}}}
void supportersSave(Writer& w,const Career& K){supportersTrim(const_cast<Career&>(K));if(getenv("FOOT_SAVE_PROFILE")){size_t c[9]={};for(auto& pr:K.supporters.profiles){auto& P=pr.second;c[0]+=P.rivalries.size();c[1]+=P.attendanceHistory.size();c[2]+=P.supporterEvents.size();c[3]+=P.gates.size();c[4]+=P.players.size();c[5]+=P.seenMatches.size();c[6]+=P.seenAttendance.size();c[7]+=P.preparedMatches.size();c[8]+=P.bookedMoney.size();}fprintf(stderr,"SUPPORTERS counts riv %zu att %zu ev %zu gates %zu players %zu seen %zu seenAtt %zu prep %zu booked %zu\n",c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7],c[8]);}w.pod(K.supporters.initialized);unsigned n=(unsigned)K.supporters.profiles.size();w.pod(n);PackW pw{w};for(auto& pair:K.supporters.profiles)profileIO(pw,const_cast<SupporterProfile&>(pair.second));}
void supportersLoad(Reader& r,Career& K,int ver){K.supporters=SupporterState();r.pod(K.supporters.initialized);unsigned n;r.pod(n);if(!r.ok||n>g_world.teams.size()||K.supporters.initialized<0||K.supporters.initialized>1){r.ok=false;return;}PackR pr(r);for(unsigned i=0;i<n&&r.ok;i++){SupporterProfile P;if(ver>=35)profileIO(pr,P);else profileIO(r,P);if(!r.ok)break;P.knownStadium[95]=P.knownTown[63]=P.knownCoach[63]=P.recordCompetition[95]=P.recordOpponentName[63]=P.recordDateText[63]=0;if(!clubValid(P.clubId)||K.supporters.profiles.count(P.clubId)||P.totalSupporters<0||P.totalSupporters>20000000||P.seasonTicketHolders<0||P.seasonTicketHolders>P.seasonTicketCapacity||P.waitingList<0||P.boycottMatches<0||P.boycottMatches>3||P.protestLevel<0||P.protestLevel>5||P.recordOpponent>=(int)g_world.teams.size()||P.rivalries.size()>16||P.attendanceHistory.size()>80||P.supporterEvents.size()>120){if(getenv("FOOT_SAVE_PROFILE"))fprintf(stderr,"SUPPORTERS rejected(1) club=%d valid=%d dup=%d tsup=%d sth=%d cap=%d wl=%d boy=%d prot=%d recOpp=%d riv=%zu att=%zu ev=%zu\n",P.clubId,(int)clubValid(P.clubId),(int)K.supporters.profiles.count(P.clubId),P.totalSupporters,P.seasonTicketHolders,P.seasonTicketCapacity,P.waitingList,P.boycottMatches,P.protestLevel,P.recordOpponent,P.rivalries.size(),P.attendanceHistory.size(),P.supporterEvents.size());r.ok=false;break;}for(int value:{P.loyalty,P.fervor,P.expectations,P.patience,P.localIdentity,P.sportingSatisfaction,P.managerTrust,P.boardTrust,P.transferTrust,P.atmosphereIndex})if(value<0||value>100)r.ok=false;P.rivalries.erase(std::remove_if(P.rivalries.begin(),P.rivalries.end(),[&](const SupporterRivalry& R){return !clubValid(R.clubId)||R.clubId==P.clubId;}),P.rivalries.end());   // anciennes sauvegardes : rivalité avec soi-même supprimée
 for(auto& R:P.rivalries)if(R.intensity<0||R.intensity>100||R.type<0||R.type>3)r.ok=false;for(auto& e:P.supporterEvents){e.reason[179]=0;if(e.type<0||e.type>11||e.intensity<0||e.intensity>100)r.ok=false;}for(auto* ledger:{&P.seenMatches,&P.seenAttendance,&P.preparedMatches,&P.bookedMoney})if(!std::is_sorted(ledger->begin(),ledger->end())||std::adjacent_find(ledger->begin(),ledger->end())!=ledger->end())r.ok=false;if(!r.ok&&getenv("FOOT_SAVE_PROFILE"))fprintf(stderr,"SUPPORTERS rejected club=%d tsup=%d sth=%d cap=%d wl=%d riv=%zu att=%zu ev=%zu\n",P.clubId,P.totalSupporters,P.seasonTicketHolders,P.seasonTicketCapacity,P.waitingList,P.rivalries.size(),P.attendanceHistory.size(),P.supporterEvents.size());K.supporters.profiles.emplace(P.clubId,std::move(P));}}

float supporterPenaltyPressure(const MatchSetup& S,int team){if(S.training||S.neutral)return 0;return std::clamp(team==1?S.supporterPressure:(S.supporterChant==CH_WHISTLES||S.supporterChant==CH_PROTEST?S.supporterPressure*.7f:0.f),0.f,1.f);}
float supporterPlayerMultiplier(const MatchSetup& S,int team,int age){return age<=21?1.f-.003f*supporterPenaltyPressure(S,team):1.f;}
